### ISSUE TITLE
Rare Drop Table - Never Drops

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#1032]
Not able to gain anything from the Rare Drop table:
Sapphire, Emerald, Rubies, Diamond, Half Keep, Loop, Left Half.
Been killing fire giants(109) and got every other drop (excluded Dragon Med) at least twice.

Anyone else been able to hit gain anything from the rare drop table?

**Comment by Christofosho** [comment]
It drops, it's just more rare from lower level npcs.
