### ISSUE TITLE
Dialog options at top left of screen clickable area offset

### ISSUE THREAD

**Issue by ZephORSC** [Open-RSC/Game#1034]
**Describe the bug**
When interacting with an object or npc and you have dialog options, the right most side of the string does not register that it is being hovered over by the mouse.

**To Reproduce**
1. Talk to any NPC that has conversation options (Banker, etc)
2. Hover over the right-most character of the string

**Expected behavior**
String should become red in color and be clickable

**Screenshots**

https://gyazo.com/9659ad8bec860e723548d113e1964d16

**Comment by Christofosho** [comment]
#1129
