### ISSUE TITLE
Missing herblaw XP from druidic ritual - STS9

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1058]
Submitted by Discord user: Engleberry

Did druidic ritual and recieved 62 herblaw xp, should get 250, which leaves me 188 xp left to get. Character name is STS9

**Comment by lmsv-mx123** [comment]
This needs to be checked for all chars having the quest, as it gave 1/4 and are unable to continue training whilst they are not level 3.

**Comment by Bl0ds** [comment]
`@Override
	public void handleReward(Player p) {
		p.message("Well done you have completed the druidic ritual quest");
		p.incQuestPoints(4);
		p.message("@gre@You haved gained 4 quest points!");
		p.incQuestExp(15, 250); // should be x4 (1000)?
	}`
in constants its added but are those in use yet and how?
`put(DRUIDIC_RITUAL, new int[] {4, Skills.HERBLAW, 1000, 0});`

**Comment by lmsv-mx123** [comment]
I don't think the map is in use yet and yes should be 1000. However, I think the fix is already placed, what's needed is the compensation of those who did the quest before, as right now if they are not level 3 cannot identify herbs.

**Comment by Christofosho** [comment]
The map needs this fix, if anyone wants to quickly commit that?
