### ISSUE TITLE
Quest Log- Ali rescue not showing as started issue

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1059]
Submitted by Discord user: Grimboe

May be the same as the issue with the quests showing up prematurely green, the prince ali rescue quest is showing up for me as not started even though i'm halfway done

**Comment by lmsv-mx123** [comment]
In authentic Runescape classic there are only two quest states - not completed (red) and completed (green), not completed includes the not started stage.

**Comment by KeplerIO** [comment]
We've fixed quest turning green right away. Not sure if that codes been released to production. But it will remain red until completed because that's how it was in original game.
