### ISSUE TITLE
Pirates treasue quest

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1060]
Submitted by Discord user: Charlie

To complete the quest I need to dig up the flowers behind  the bench but nothing interesting happens. Tried both flowers from multiple positions, clicking dig on spade and also using spade with flower

**Comment by Bl0ds** [comment]
![peek 2018-11-01 18-34](https://user-images.githubusercontent.com/26518731/47865603-49d99880-de05-11e8-850e-ad227190b990.gif)
