### ISSUE TITLE
Bank Pin Menu Bug/Not Working

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#1067]
**Describe the bug**
A clear and concise description of what the bug is.Talk to banker to open bank. first menu is kosher, and it opens the menu again after selecting "id like to acces...", the second menu is the same, with the "id like to talk about bank pins" added to the bottom.

Additionally, I can't set a bank pin in game.

**To Reproduce**
Talk to banker.
Select to open bank.
See menu again.
Select to set bank pin.
nothing happens.

**Additional context**

**Comment by Marwolf** [comment]
b76e0a1a2d410efee6e8f7b4cd1819c0662cf2b1 fixed banker menu but the bankpin interface does not load to set a pin. Has not been able to open since initial RSCL import.
