### ISSUE TITLE
Chaos druid drops

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1068]
Submitted by Discord user: Engleberry

Dropping unholy symbol moulds without quest completion. Also not dropping double herb drops, not dropping filled vials, not dropping near enough the same rate of herbs at all.

**Comment by Christofosho** [comment]
Not dropping double herbs? Is this still true?

**Comment by Christofosho** [comment]
Chaos druids do not drop double herbs.
http://www.bishopd.com/mainpages/games/rsc/drops/rsc_drops.html#begin

**Comment by lmsv-mx123** [comment]
![image](https://user-images.githubusercontent.com/10690767/47964860-1a917a00-e005-11e8-92a2-643a357c4ead.png)
Chaos druid and warrior have the multiple herb chance

**Comment by Christofosho** [comment]
#1077 for herbs
