### ISSUE TITLE
Prince Ali partial coin reward before quest end not working

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1069]
Submitted by Discord user: Grimboe

During the Prince Ali Rescue Quest at one point in the quest you are supposed to be able to get 80 coins of your reward early as compensation for giving the spymaster the key mould and a bronze bar, the dialogue telling you that you can do so is still there but if you talk to hassan he says the spymaster can authorize payment etc, you can still get the full reward at quest end and if i recall from the original if you do this you just get 80 less coins at the end so this is a very tiny issue

**Comment by lmsv-mx123** [comment]
Should be fixed in #1080
