### ISSUE TITLE
NPC aggressive behaviour doesn't appear to be implemented right

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#107]
I was attacked by level 13 rats while standing in the Varrock wildy. Typically NPCs don't attack anyone 2x or more their level. ** This is normal, behaviour, the rule doesn't apply in wildy.

Ensure that the 2x level rule applies outside of the wildy.

The RSC Preservation folks have mentioned some NPCs don't follow the rule.
http://runescapeclassic.wikia.com/wiki/Aggressiveness

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
