### ISSUE TITLE
Seamen overly concerned about their wives and children

### ISSUE THREAD

**Issue by ZephORSC** [Open-RSC/Game#1086]
**Describe the bug**
In Port Sarim and the Ardy port, the Seamen (Captain Tobias, Seaman Thresnor, Seaman Lorris, Captain Barnaby) have wrong dialog if you walk away without answering them. It appears to be from dialog from the Dragon Slayer quest if you ask them to take you to Crandor.

**To Reproduce**
1. Go to Port Sarim.
2. Talk to Captain Tobias
3. Click out of the dialog without answering them.
4. Walk away.

**Expected behavior**
Sailors should appreciate that they have living wives and children. Also, nothing should happen.

**Screenshots**

https://gyazo.com/346d2f7f7268487ffdd0985bf21937e7

**Comment by lmsv-mx123** [comment]
Fixed in #1090
