### ISSUE TITLE
Authentic Bug: Tourist Trap

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#1095]
**Describe the bug**
While completing Tourist Trap, when you go to make the "prototype dart tips", if you drop the prototype, you can make an additional prototype dart tip. This would work continuously until you completed the quest. The mechanics still worked otherwise, i.e. chance to make/not make a dart tip, use feathers each time you make one, chance to use the bronze bar/not use the bronze bar(as in, it gets pulled out of inventory). So by dropping the prototype dart tip, you could make thousands of them. 

**To Reproduce**
1. Make prototype dart tip
2. drop prototype dart tip
3. make another prototype dart tip

**Expected behavior**
This is the authentic behavior. It is also documented that you could make more than one in the wiki. http://runescapeclassic.wikia.com/wiki/Tourist_Trap

**Additional context**
In RSC real, I had over 1000 prototype dart tips in my bank(pic not included, other computer). The fletching xp for making them was also higher than anything else in game, and would go up 25 xp per fletching level you had.

**Comment by KeplerIO** [comment]
I’m guessing it’s the case currently that is not possible?

**Comment by lmsv-mx123** [comment]
Didn't actually know that the xp they gave was level dependent :0 You are right about that, however, by seeing by replay it didnt go up as much. It seems it was 12.5xp per each level

**Comment by lmsv-mx123** [comment]
Should be fixed in #1166
