### ISSUE TITLE
Server online, but can't log in

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1100]
Submitted by Discord user: Gd1

Tried to log in at the time of this bug report -2 minutes. OpenRSC window launcher goes black for some number of seconds and then flashes the message very briefly that you get when you lag out and disconnect and then kicks me back to the sign in screen.

**Comment by Marwolf** [comment]
The 2am to 3am (EST) daily server crash issue is being worked on. We are analyzing the heap dump and thread dump to figure out the bug.
