### ISSUE TITLE
Chat print without name of player sending message

### ISSUE THREAD

**Issue by ZephORSC** [Open-RSC/Game#1112]
**Describe the bug**
Witnessed a player send a message in chat without it being prefixed by the player's name.

**To Reproduce**
1. Have not seen reproduced

**Expected behavior**
Prefix message with player name

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/48236927-6724de80-e392-11e8-88f6-28d56fece772.png)

![image](https://user-images.githubusercontent.com/995993/48236931-6a1fcf00-e392-11e8-94f5-c8d720d99824.png)

**Desktop (please complete the following information):**
- Windows 10
- java version "1.8.0_181"
- Java(TM) SE Runtime Environment (build 1.8.0_181-b13)

**Comment by Marwolf** [comment]
Need to see if this can be replicated more.

**Comment by Christofosho** [comment]
Resulted from wonky packets in a prior update.

**Comment by ZephORSC** [comment]
Had this happen again 11/22

![image](https://user-images.githubusercontent.com/995993/48925469-d79f2580-ee91-11e8-9eb0-82a11de0e603.png)

**Comment by multi-talented** [comment]
I was the one that said "lol" in the message. It may have something to do when players that speak as they enter the area and haven't been cached by another players client (Zeph in this case) yet, it'll occur.

**Comment by Marwolf** [comment]
This should now be corrected. Have not had any reports since.
