### ISSUE TITLE
Right click name: Add Ignore

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#1127]
**Is your feature request related to a problem? Please describe.**
In RSC you could right click a players name in the chat area, and add or ignore the player.

**Describe the solution you'd like**
Do Eet.

**Additional context**
People don't ride Zebra's because they can't be tamed like horses, they will still revert to their wild instincts when threatened or in a bad mood.

**Comment by Christofosho** [comment]
can only report / message on right-click.
