### ISSUE TITLE
Verify constraint of quests with skill level requirements to complete

### ISSUE THREAD

**Issue by lmsv-mx123** [Open-RSC/Game#1153]
**Describe the bug**
Same as title

**To Reproduce**
For instance temple of Ikov should not be completable if the player has less than 42 Thiev

**Expected behavior**
Have the player meet level requirements either directly or by boost to complete the quests having skill level requirements.

**List**
- [x] Knight's sword (Mining lvl 10)
- [x] Dragon slayer (Magic lvl 33)
- [x] Hero's quest (Herblaw lvl 25, Mining lvl 50, Fishing lvl 53, Cooking lvl 53)
- [x] Family Crest (Mining lvl 40, Smithing lvl 40, Crafting lvl 40, Magic lvl 59)
- [x] Fishing Contest (Fishing lvl 10)
- [x] Temple of Ikov (Thieving lvl 42, Ranged lvl 35)
- [x] Sea Slug (Firemaking lvl 30)
- [x] Underground pass (Ranged lvl 25, optional Thief 50)
- [x] Tourist Trap (Fletching lvl 10, Smithing lvl 20)
- [x] Digsite (Thieving lvl 25, Agility lvl 10, Herblaw lvl 10)
- [x] Legends Quest (Mining lvl 52, Agility lvl 50, Crafting lvl 50, Strength lvl 50, Woodcutting lvl 50, Herblaw lvl 45, Prayer lvl 42)
- [x] Lost City (Crafting lvl 31, Woodcutting lvl 36)
- [x] Scorpion Catcher (Prayer lvl 31)
- [x] Tribal Totem (Thieving lvl 21)
- [x] Shilo Village (Agility lvl 32, Crafting lvl 20)
- [x] Observatory Quest (Crafting lvl 10)
- [x] Watchtower (Herblaw lvl 14, Magic lvl 14, Thieving lvl 15, Agility lvl 30, Mining lvl 40)

**Comment by lmsv-mx123** [comment]
Most if not all are placed in code I think, aside the watchtower thieving requirement which I haven't identified where it is supposed to be.

**Comment by Christofosho** [comment]
I'll close the issue and if anything comes up we will know. :P
