### ISSUE TITLE
Establish dialogue with appropriate doormen on zanaris marketplace

### ISSUE THREAD

**Issue by lmsv-mx123** [Open-RSC/Game#1164]
**Describe the bug**
When inside the market, the player should get into dialogue with doormen of inside the market, outside of it from the outside doormen

**To Reproduce**
Be inside the marketplace and outside doormen gets tagged into dialogue

**Expected behavior**
Tag the correct doormen inside bounds

**Screenshots**
![doormen](https://user-images.githubusercontent.com/10690767/48531199-f59cd280-e860-11e8-8056-fe2515942b41.gif)

**Comment by KeplerIO** [comment]
I do not believe you need a diamond to leave.. only to enter.. leaving should target no dialog if I remember the area correctly.

**Comment by lmsv-mx123** [comment]
Yes the diamond is needed, got some replays of that. If the player has no diamond once inside, then they need to use the escape ladder

**Comment by KeplerIO** [comment]
Understood. Self-Assigning.

**Comment by Christofosho** [comment]
This done?
