### ISSUE TITLE
Imp health

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1204]
Submitted by Discord user: Chanizu#4444

Imps do not regenerate health over time, this leaves me at risk of getting health experience. Please fix

**Comment by Marwolf** [comment]
Verified that NPCs are not regenerating HP.

**Comment by Christofosho** [comment]
We finally have a source showing npcs regenerating : we did not fix this in the past because we were waiting until we had proof. :)

**Comment by Christofosho** [comment]
TODO: Do all npcs and players regenerate on the same tick? Or should each have their own event?

**Comment by Marwolf** [comment]
I'd say just stick them on the same tick.

**Comment by Christofosho** [comment]
#1357
