### ISSUE TITLE
Falador Gem Seller

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1211]
Submitted by Discord user: xxxfreexxx

Gem Seller NPC in Falador is missing.......................................

**Comment by Marwolf** [comment]
I see Gem Merchant in East Ardougne in the wiki but not Falador

https://openrsc.com/wiki/index.php?title=Gem_merchant

**Comment by Marwolf** [comment]
Verified shop NPC is missing.
https://openrsc.com/wiki/index.php?title=Herquin%27s_Gems
