### ISSUE TITLE
Restless Ghost Skeleton

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1214]
Submitted by Discord user: xxxfreexxx

The Lvl 19 Skeleton in the lower floor of the Wizard's Tower does not work as intended during the Restless Ghost quest. When the skull is taken he is supposed to spawn and attack you, currently he just sits on the other side of the wall and does nothing. He is meant as a deterrent to brand new players.

**Comment by lmsv-mx123** [comment]
Only spawn if there is no skeleton in the area (and is your first time trying to grab skull), could be a path issue to prevent getting very far from the skull though

**Comment by Christofosho** [comment]
Skeleton did not path around the cage when the skull was obtained. Stupid, but authentic.
