### ISSUE TITLE
Chaos druid edgeville 2 herb drop

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1244]
Submitted by Discord user: Saiyen X

Killing Chaos druids in the edgeville dungeons and I sometime gets 2 herb drops per kill.

**Comment by Marwolf** [comment]
Per Luis123.intl on Discord:

> Killing Chaos druids in the edgeville dungeons and I sometime gets 2 herb drops per kill. that is authentic behavior @Saiyen X
> not common but possible
