### ISSUE TITLE
Players are able to walk through NPCs that shouldn't be able to walk through. (non-kosher)

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#1262]
The Monk of Zamorak (both level 19 & 29) are currently walkthrough able when they shouldn't be. Located by the far west entrance of wilderness.

**Comment by Marwolf** [comment]
This should now be fixed with the recent update. Needs to be tested.

**Comment by multi-talented** [comment]
Just to clarify, that not all npcs are walk-throughable and not all npcs are not walk-throughables. Only certain npcs (like the zamorak monks) can block players from crossing through them.

**Comment by multi-talented** [comment]
https://youtu.be/B2p5R353_V4?t=50
