### ISSUE TITLE
Farmer=63 dialogs should be the same as man=11. Verify 319 and 434 have the dialogs in real RSC.

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#131]
Man and Farmer are known to have the same dialogue.
Pirate has a separate set of rotating dialogues.
RSC Preservation Project has a replay with all the dialogue.

**Comment by Marwolf** [comment]
@Kenix3
Farmer NPCs 63, 319, and 434 do not respond when talked to.

Fred the Farmer 77 does talk but it is his unique version.


Pirate NPCs 137 and 264 have a general pirate dialog that rotates.
Redbeard Frank 128 has a unique pirate dialog.
guard (pirate) 258 speaks and then attacks even when invulnerable.

https://runescapeclassic.wikia.com/wiki/Pirate/Dialogue

Dialogs look good.

**Comment by Kenix3** [comment]
Farmer 63 should have the same dialog as man 11. The other IDs we can verify with the RSC preservation people.

**Comment by Marwolf** [comment]
Is this still needed to be worked on?

**Comment by Kenix3** [comment]
We need to verify in world tour replays that these NPCs don't exist in kosher game before we close the issue.
