### ISSUE TITLE
Certain agility obstacles don't allow you to attempt them when you are at 100% fatigue

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#132]
Obstacles courses don't let you at 100% fatigue unless you would otherwise be stranded by being allowed to do it. Each obstacle has custom messages.
There are some known in the Tree Gnome course.
Shortcuts and quest agility are yet untested.
Get with the RSC Preservation folks to figure out exactly which obstacles do not let you attempt.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
