### ISSUE TITLE
2.1.0: King Black Dragon Overpowered

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1334]
Submitted by Discord user: Millz

Since the update king black dragon is incredibly overpowered.

With 94 defence and full rune, I'm getting hit >20 x3. This has changed drastically from the under powered version earlier today.

https://www.youtube.com/watch?v=HmyasVbmPpE -> This guy is 99 defence so similar to my current level and barely getting hit. Lots of 0s, the odd big hit.

https://www.youtube.com/watch?v=aE3hCvcqyeY -> 64 defence. Lots of 0s and low numbers but the odd 22/21 - expected at that defence level...

Thanks

**Comment by Christofosho** [comment]
https://www.youtube.com/watch?v=VNM2SaPZaXU
