### ISSUE TITLE
Implement correct duel in the wilderness behaviour

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#134]
In official RSC the duel option is missing from the right click menu when you are in the wildy.
Criteria is both players in wildy then Duel option is replaced by Attack.
If one player is in wildy, and the other outside of it, then the duel can commence in wildy by the two players meeting in the middle.

**Comment by Marwolf** [comment]
![Image](https://i.imgur.com/5JBlR2M.png)

Dueling requests from one player in the wilderness and one outside will send (player outside can send) but player standing inside does not send a duel request when attempted (no error)

**Comment by Kenix3** [comment]
This is incorrect behaviour. They should be able to complete the duel. The [Duel] menu item only changes to [Attack] when BTOH players are in the wilderness.
