### ISSUE TITLE
Coin Chest Next to Nature Rune Chest

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#1344]
**Describe the bug**
The coin chest next to the ardounge nature rune chest is out of place by 1 square. It should be against the wall.
![untitled](https://user-images.githubusercontent.com/36169371/49685022-9c525700-fb1f-11e8-90f8-fa65d1a7f7e4.png)

**Additional context**
Horses have long bushy tails so you don't have the stare at their asses, like cats.....fucking cats...

**Comment by Christofosho** [comment]
this is how it should be
