### ISSUE TITLE
Can't tele grab through gate

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#1367]
**Describe the bug**
Unable to telegrab through gates(or at least in varrock bank basement gate)

**To Reproduce**
https://gyazo.com/b16c21ce3a40b92221fd8c21b0bd4e4a

**Expected behavior**
Lemme telegrab that golddddd!

**Additional context**
Koreans don't have public trashcans. Businesses just leave piles of trash outside by the wall, and people put there trash in the pile.

**Comment by Christofosho** [comment]
#1373
