### ISSUE TITLE
Betty Magic Shop Restock

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#1368]
**Describe the bug**
The runes in Betty's Magic Shop in port sarim seem to restock too quickly. I don't have proof other than other shops, but the runes replenish much quicker than other shop stock around runescape.

**Additional context**
I liek turtles.

**Comment by Marwolf** [comment]
Will need a reply before this can be actioned.

**Comment by lmsv-mx123** [comment]
I dont have not a replay for this sadly, but a memory of around what the shop restock rate should feel like
