### ISSUE TITLE
Lost all but 3 items via dual

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1390]
Submitted by Discord user: Kittycatrock

Dualed someone in the party room at seers for a quick teleport to lumby but lost all my items except for the 3 worth most. I believe in old rsc you only used to lose the items you staked

**Comment by Christofosho** [comment]
Wow! No one has experienced this before. We are working to test what made this bug occur.

**Comment by Marwolf** [comment]
Tried to replicate and didn't loose any items in party room dueling rick.ibm when I died.

**Comment by Marwolf** [comment]
`
boolean stake = getDuel().isDuelActive() || (player != null && player.getDuel().isDuelActive());
(edited)
public void resetAll() {
`

`public void resetAll() {
        resetAllExceptTradeOrDuel();
        getTrade().resetAll();
        getDuel().resetAll();
    }`

**Comment by Christofosho** [comment]
#1392
