### ISSUE TITLE
NPC respawn health bar

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1412]
Submitted by Discord user: Christopher, ORSCN: Talcron

When NPCs respawns they show a 20ish percent healthbar over their heads for a brief moment. I dont know if this is a bug, but it would be better if this bar were full HP or didnt even show.

**Comment by Christofosho** [comment]
Hey there,

Thank you for your report. This is authentic behaviour which happened in the original game. As such it won't be fixed for the time being.
