### ISSUE TITLE
Registering accounts on android

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1413]
Submitted by Discord user: Kittycatrock(jenny) 

If you try and register a new account on Android, it will always say that you have tried registering too many accounts in the past hour, even if it is the first attempt. If you entered in a name to register, that name will be forever taken by the server if you try to register it correctly on pc. The password you put in on Android for your supposed new account will not work. Additionally, if you try and register another account, it will say your email address was taken by the fake ghost account. This bug seems to be 100 percent consistent... I am using android pi.

**Comment by Marwolf** [comment]
Fixed in #314743b99bcaf3e2f7270e92969c0ee668c702ff
