### ISSUE TITLE
mobile users are not present at homepage

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1422]
Submitted by Discord user: sillu012

Live map + 'players online' do not show players who are on phone... I have noticed that J E N N Y and Heather are sometimes not visible there. Heather told me she is on phone right now when I'm writing this report :)

**Comment by Marwolf** [comment]
This appears to be only related to the J E N N Y username and may have to do with all the spaces. Players with a single space or no spaces that are PC client and Android client appear to be unaffected after testing. Could not replicate for Heather.
