### ISSUE TITLE
Poisoned Rune Spear

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1426]
Submitted by Discord user: kaibo

in RSC wiki: "Due to an oversight the poisoned rune spear has no skill requirements to wield, which may otherwise be considered a glitch. The non-poisoned version requires 40 Attack and 35 Ranged to wield. " this is not the case in openRSC. Poisoned rune spear still requires 40 attack and 35 ranged to wield.

**Comment by lmsv-mx123** [comment]
This glitch should be for any poisoned spear.
