### ISSUE TITLE
Can create bearded lady without packet manip

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#1456]
**Describe the bug**
In the character creation tool, the player is not prohibited from creating a bearded lady. This is an authenticity bug in the client.

**Expected behavior**
Should be prohibited from creating this kind of character unless using a hacked client. Possibly make a hidden option for it in some client config file.

**Comment by Marwolf** [comment]
Bearded ladies were created using WPE packet editing.

**Comment by Hubcapp** [comment]
In OpenRSC, bearded ladies are created through the player creation menu. As far as I know, there is no option in the client to restrict yourself from creating that kind of account, as it would have been authentically.
