### ISSUE TITLE
[for the record] Some NPCs authentically do not check your gender.

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#1461]
- Grandpa Jack doesn't care if you're female: see around 4 minutes of `08-04-2018 12.59.21 fishing contest quest` "( QUEST) Grandpa Jack: Hello young man"

- Brother Kojo doesn't care if you're female: see around 5 minutes of `08-03-2018 16.07.39 clock tower female dialogue, then on to slaughter gnomes at battlefield, progressing onward to observatory` 
"( QUEST) Brother Kojo: Oh thank you kind sir"

**Comment by lmsv-mx123** [comment]
Holgart doesn't care if you're male: "(QUEST) Holgart: well hello m'laddy"

**Comment by lmsv-mx123** [comment]
These need to be checked on:
Jeremy Servil: I'm Jeremy Servil
Jeremy Servil: Please sir, don't hurt me

Player: What does Bwana mean?
Trufitus: Gracious sir, it means 'friend'
Trufitus: And friends come in peace

Beggar: Please sir, me and my family are starving
Beggar: Could you possibly give me a loaf of bread?

Player: i could go and take a look for you if you like
Almera: would you kind sir?

hadley: or to wander the beautiful hill sides
Player: it is quite pretty
hadley: surely pretty is an understatement kind sir

**Comment by Hubcapp** [comment]
```
( QUEST) Elena: what are you doing back here
(OPTION) I just find it hard to say goodbye sometimes
(OPTION) I'm afraid I've lost some of the stuff that you gave me...
(OPTION) i've forgotten what i need to do
( QUEST) Tylerbeg: I just find it hard to say goodbye sometimes
( QUEST) Elena: Yes...I have feelings for you too...
( QUEST) Elena: Now get to work!
```
Is Elena bisexual? more questions that may never be answered

**Comment by lmsv-mx123** [comment]
wonder what happened when a bearded lady talked to her lol
