### ISSUE TITLE
Mining clay does not give right amount of xp

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1486]
Submitted by Discord user: sillu012

Mined some clay, noticed xp was slow (lvl 1). Seems to be between 1-2 xp per ore.

**Comment by KeplerIO** [comment]
Do we know where this player was mining within the game? Might be important to check specific ground objects ie the rock nodes.

Can confirm clay should be 5xp ea. I’ll validate further from replay.

**Comment by Christofosho** [comment]
#1490 also includes this clay fix.
