### ISSUE TITLE
DD on players - Non-Kosker/Bug

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#1504]
**To Reproduce**
1. when player1 stands in one spot
2. then player2+ clicks to go in that spot
3. In ORSC, player2+ goes to that spot

**Expected behavior**
steps 1 and 2 above are correct but...
3. In real RSC, player2+ doesn't respond because their is another player in that spot.
4. Player2+ has to click the space on the opposite side of player1 to walk there and click player1's spot after player2+ starts walking over player1 to be able to DD.

**Comment by kInGkRiStOf** [comment]
Add to this that when following, if the leader stops, you will travel onto the same spot as the leader, instead of stopping behind them.

Maybe a separate issue, but it sounds similar.

**Comment by Christofosho** [comment]
You could always click to walk onto another player. I agree with the secondary comment by Kris, this should be made into a separate ticket.
