### ISSUE TITLE
You can pick up items from one tile away

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#151]
Official behaviour is that you must be standing on the same tile as the item.

**Comment by ipkpjersi** [comment]
This should probably be re-opened, I can still replicate this bug. I can still pick up items either two or three tiles away.

**Comment by Kenix3** [comment]
Yeah, sometimes the fix works and sometimes it doesn't.

**Comment by Kenix3** [comment]
Resolved in 73e67ac
