### ISSUE TITLE
Mining with low mining & bronze pickaxe

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1510]
Submitted by Discord user: Warchas

I Went to barbarians South of edgeville and started mining at the coal rocks.
It started swinging with an iron pickaxe above my head ( the Icon was iron pickaxe). Then it swung forever, "You only succeed at scratching the rock" and then it kept swinging making it impossible to move and even impossible to logout.

I had mining skill 1 using bronze pickaxe.

**Comment by KeplerIO** [comment]
I cannot reproduce this in the current branch. Have an account with 1 mining and bronze pickaxe. Attempted to mine coal and I did not succeed in mining. The action was stopped and I was free to move my character. I tried on the tin ore that are there also. "Spam" clicking the nodes does not cause any unexpected behaviors.

**Comment by KeplerIO** [comment]
New info: The reporter of this issue contacted me on Discord to clarify, they believe this issue is related to batching. Still no recreation of the issue to date.

**Comment by Kenix3** [comment]
Discord user Warchas should verify the server he is running has batching turned off.
