### ISSUE TITLE
Add command to reset prayer

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#1528]
Would be same as ::heal and ::sethp, but changes prayer instead

**Comment by multi-talented** [comment]
Setting your prayer level to the desired (::set prayer 99) level automatically restores it to it's own desired restoration level, always making it 99/99 after committing the command.

**Comment by Kenix3** [comment]
Correct. This is to set the _current_ prayer level as opposed to _max_ prayer level. Similar to the sethp command.
