### ISSUE TITLE
Ardy furnace

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1554]
Submitted by Discord user: Fred West

Glitch at Ardy furnace, use ores with furnace and it says ''you place the item in the chest'' and takes the ores.

**Comment by Kenix3** [comment]
Having trouble replicating this.

**Comment by KeplerIO** [comment]
I cannot recreate this issue by trying to smith any bar at any given smithing level. You are either rejected from smithing the bar or the bar is produced. In events where you do not have the level or proper materials or any combination therein, proper behavior is shown.

This was tested only on latest branch on 2.0.0. I do not have the proper levels to test this in production.

**Comment by Kenix3** [comment]
Closed due to inability to replicate on current code.
