### ISSUE TITLE
Muddy Herbs should be identifiable instead

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#157]
"When herbs are first obtained as drops from monsters, they are unidentified. Unidentified herbs stack in your bank according to their type. In order to be able to use these herbs to make potions, a player must identify what the herb is by clicking on it in the inventory screen. Different herbs require different levels to identify."
https://runescapeclassic.wikia.com/wiki/Herblaw

As a level 1 herblawist, I can still see muddy taramin, muddy ranarr, etc. Should not be able to see anything other than an unidentified weed until level to clean it.

**Comment by Kenix3** [comment]
It looks like RSCE (our original code base) replaced Identify with Clean. We'll want to implement Identify behaviour. Probably allow for this to be configurable by the server operator as this is a decent Quality of Life improvement. It's easy to cheat unid herbs as that info is in client, so the purpose is lost anyway.

**Comment by Kenix3** [comment]
#205 to track the issue of being able to clean/identify them below the correct level.

**Comment by Christofosho** [comment]
May I comment out the current named herbs in the database, and add them all with the name "herb" for now? :)

**Comment by Christofosho** [comment]
All that is left is configuration.
