### ISSUE TITLE
Flax plants never dissapear when picking them.

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1618]
Submitted by Discord user: Hounded

When picking flax you can stand on the same plant and pick a full inventory... the plants never dissapear or move... in rsc you would get from like 2-8 flax (something like that) then the plant would dissapear... and youd have to move to another.

**Comment by Kenix3** [comment]
Needs replay verification

**Comment by Marwolf** [comment]
No replays were found for flax picking.
No youtube videos found.

https://classic.runescape.wiki/w/Flax
No reference to respawn.

https://runescape.fandom.com/wiki/Flax

> The key to fast flax picking involves timing; Try to find 5 flax plants in a plus-shaped position and stand in the middle of it, then start picking the flax in a circular motion by clicking a plant and then, when you're about to hear the "pop", click the next plant. Your avatar will show the picking motion once while actually picking 2 flax. Eventually a plant will run out, that's when the centre plant right below you comes into play. Use this plant as a substitute until the other plant(s) respawn. This way you can pick 28 flax in about 30 to 35 seconds.

OSRS and RS3 have flax respawn only.
