### ISSUE TITLE
Sleeping bag disconnect and stacking on players/monsters

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1620]
Submitted by Discord user: Warchas

Not sure if it has been mentioned before but every now and then you randomly disconnect whilst clicking your sleeping bag. Another thing I’m trying to remember is that if you weren’t able to stack on players / monsters? I want to remember that in wilder when a player died and the items finally showed after x minutes everyone stacked to loot? Am I wrong?

**Comment by Marwolf** [comment]
Need specific instructions to repeat these.

**Comment by Marwolf** [comment]
RSC+ replay located that is named something along the lines of "sleeping still logs out after 5 minutes of inactivity"

No information about what stacking on players / monsters means.

Drop visibility was investigated for wilderness and non wilderness using rsc+ replays and corrected recently.
