### ISSUE TITLE
Smelting Iron Ore at 100% instead of 50%

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#163]
**Describe the bug**
When smelting iron ore you always get an iron bar, it's supposed to be a 50% chance.

**To Reproduce**
1. Go to a furnace (my case Al Karid)
2. Click on Iron Ore

**Expected behavior**
Smelted 60 iron bars straight.
When smelting iron ores, you're supposed to lose 50% of the times smelting ores, gaining no exp nor bar.

**Screenshots**
http://prntscr.com/kf53uy
http://prntscr.com/kf54sn

**Comment by Kenix3** [comment]
Fixed in 7709985
