### ISSUE TITLE
Server crash on opening single player rsc master, player aleady logged in, and ranking.

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1638]
Submitted by Discord user: Varrock

Laptop is 2gb ram windows 10 with a solid state 64gb harddrive
I click on run open rsc press 1 for start game. Server crashes immediately. Ive been told by dev on discord the issue is that the client is opening before the server is ready. I have to close all command prompts and try again 3 to 5 times each time I want to log in. Another bug I found is that if i get disconnected from 5 minute timer or random disconnection. When I go to log back in it says my character is still logged in pleaee try again. Then I have to repeat my 3 to 5 reloads to log back in. Finally if i rank my character as an admin the the client comes up grey and i have to redownload to getvit to work again. Other than that this is fantastic love it and thank you.

**Comment by Marwolf** [comment]
Need to know the exact version of java installed:

command prompt -> "java --version"
