### ISSUE TITLE
Silk buy/sells for 0 gp at varrock clothing store [Bug]

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#164]
**Describe the bug**
Silk cost 0 to buy, and 0 to sell.

**Screenshots**
http://prntscr.com/kfa2xt
http://prntscr.com/kfa3yk

**Additional context**
According to wiki it should cost 30 gp to buy silk, and should give you 16 gp to sell one.

**Comment by Tessalicious** [comment]
Fixed in LIVE server
