### ISSUE TITLE
[Single-player] Logging out prevents relogging until client is restarted

### ISSUE THREAD

**Issue by twothousandandone** [Open-RSC/Game#1644]
**Describe the bug**
In the single-player build of Open RSC, if an account is logged out in any manner (idle timer, or purposeful log out), attempting to log back in will produce the _"That username is already logged in. Wait 60 seconds then retry."_ message, and prevent relogging.

Different user accounts may still be logged into without restarting the client until they have been logged out also. 

An issue regarding random forced log outs has also been opened and may be found here:  https://github.com/Open-RSC/Game/issues/1645

**To Reproduce**
1. Log into an account in the single-player build of Open RSC
2. Log out purposefully or by waiting for the idle timer
3. Attempt to log back in
4. See error _"That username is already logged in. Wait 60 seconds then retry."_
5. Restart the client and attempt to log in, which will fix the problem (temporarily)

**Expected behavior**
Logging out should not cause the _"That username is already logged in. Wait 60 seconds then retry."_ message or prevent log in

**Screenshots**

![java_2019-02-10_08-40-22](https://user-images.githubusercontent.com/47410572/52534550-fa164180-2d10-11e9-994d-16c41eddf564.png)

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by Marwolf** [comment]
Going to use #1645 as the tracking for login prevention config.
