### ISSUE TITLE
Goblin Diplomatic - Unable to start [Bug]

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#167]
**Describe the bug**
After talking to one of the generals I did not get any dialog option, and trying to speak to either general again gives following error:
http://prntscr.com/kfc098

**To Reproduce**
1. Try to start Goblin Diplomacy

**Screenshots**
http://prntscr.com/kfc098

**Additional context**
Quest did not start is still red in your quest log.

**Comment by Fefect** [comment]
Talk to the Bartender in Port Sarim. He's located in The Rusty Anchor in the building beside the fence separating Port Sarim and Draynor Village in order to start the quest.
1637180 should resolve any issues with the quest freezing the player.

**Comment by Fefect** [comment]
Resolved in 1637180
