### ISSUE TITLE
Random items found in otherwise inaccessible area

### ISSUE THREAD

**Issue by twothousandandone** [Open-RSC/Game#1689]
**Bug**
Several quest items are randomly found near the coordinates **15, 15** and **50, 50** in Open RSC.

Removing these may be considered in an attempt to ensure further authenticity.

**To Reproduce**
1. use the ::teleport command to go to 15, 15 or 50, 50
2. Observe the stray quest items 

**Screenshots**
![java_2019-02-16_15-36-18](https://user-images.githubusercontent.com/47410572/52905025-e16ec580-3201-11e9-8073-c1f09eac19f3.png)
![java_2019-02-16_15-35-00](https://user-images.githubusercontent.com/47410572/52905026-e29ff280-3201-11e9-9763-438ac312c732.png)

**Comment by kInGkRiStOf** [comment]
Coordinate 1,1 also has objects

**Comment by lmsv-mx123** [comment]
Fixed the two firsts in #1693
