### ISSUE TITLE
Bear do not drop Bear meat & Missing Bears [Bug]

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#171]
**Describe the bug**
Killing bears do not drop bear meat or any kind of meat just bones. [Attempted in wildness lvl 11]
+Missing bear spots: (unable to find) South of Draynor and Varrock East Mine

**To Reproduce**
Kill Bears

**Expected behavior**
No meat will drop.

**Screenshots**
http://prntscr.com/kfhra5
http://prntscr.com/kfhsed

**Additional context**
Make Druid Ritual hard/impossible to complete.

**Comment by LionRsc** [comment]
Bears in wildy still missing the drop. Was only able to kill one, so might not be all of em. (above edge)

**Comment by Marwolf** [comment]
@LionRsc was this verified on the dev server? Has the current commit master on it.

**Comment by LionRsc** [comment]
I'm only playing the normal server not the dev. Guess I misunderstood. (Was not able to find the bears east of draynor either) My bad.
Is there a way to see when the update is implemented into the normal server?

**Comment by ipkpjersi** [comment]
The normal server gets updated during a weekly update window, I believe on Sunday.
