### ISSUE TITLE
Cant enter McGrubor's Wood 

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#1712]
Submitted by Discord user: Puar

You can't enter "McGrubor's" Wood even after pushing the fence with loose pannels

**Comment by Marwolf** [comment]
![screen_shot_2019-02-17_at_7 00 44_pm](https://user-images.githubusercontent.com/16737510/52926084-55909280-3302-11e9-8f7b-49b362f7e3ce.png)

**Comment by kInGkRiStOf** [comment]
We verified once you start the quest "Plague City" in ORSC, you can then enter the woods. Fishing Contest needs to be verified as well.
Authentic implementation needs to be checked before proceeding with or without a change to behavior.

**Comment by lmsv-mx123** [comment]
You didnt need to have started fishing contest to get into that place, as you could get the worms before the quest

**Comment by lmsv-mx123** [comment]
See attached replay, Shaun entered into the area without having started Fishing Contest
[06-21-2018 10.07.53 scorpion catcher AND fishing contest AND murder mystery.zip](https://github.com/Open-RSC/Game/files/2891188/06-21-2018.10.07.53.scorpion.catcher.AND.fishing.contest.AND.murder.mystery.zip)

**Comment by kInGkRiStOf** [comment]
Okay, I would take that as verification of both quests not being required before being able to access it.
