### ISSUE TITLE
Gnome Femi Doesn't Ask For Help

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#1724]
**Describe the bug**
The gnome Femi at the front of the gnome stronghold is busy, and doesn't ask for help from the player. The wiki states:
`Femi is a non-player character who stands beside a cart just south of the Gnome Stronghold gate. When players first attempt to enter the stronghold, Femi will interrupt and ask for help carrying some heavy boxes. There is a choice to either accept or decline. Either way, the stronghold can be entered.`

https://classic.runescape.wiki/w/Femi

**Comment by lmsv-mx123** [comment]
A bit more info the gate id is: 626

**Comment by twothousandandone** [comment]
Does Femi always ask? Or do they only ask once?

I thought they only asked during the events of a quest

**Comment by kInGkRiStOf** [comment]
Only during the initial entry.

**Comment by lmsv-mx123** [comment]
Can confirm on that never got asked during a quest or any special event afterwards and have not seen such case
