### ISSUE TITLE
Gertrude NPC, has no dialog/can't start gertrudes quest [Bug]

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#174]
**Describe the bug**
Gertrude does not talk, and you cannot start Gertrude quest.

**To Reproduce**
1. Go to Varrock
2. Talk to Gertrude

**Expected behavior**
Gertrude will face you, not say anything and quest will stay red(not started)

**Screenshots**
http://prntscr.com/kfltms

**Comment by Kenix3** [comment]
Gertrude's Cat quest is currently unimplemented.

**Comment by Christofosho** [comment]
Working in v2
