### ISSUE TITLE
Implement Missing Fishing Contest Behaviour

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#175]
**Describe the bug**
No lvl 46 Guard dogs patrol the red wines (none to be seen).
+Sinister Stranger don't have dialog, inside the fishing competition.

**To Reproduce**
1. Go to McGrubor's Wood. 
+Go to fishing competition.

**Screenshots**
http://prntscr.com/kfm4g2
http://prntscr.com/kfm4s7

**Comment by Kenix3** [comment]
This is related to all quests and miniquests and minigames not being implemented yet.

**Comment by LionRsc** [comment]
Ahh thanks, was able to finish the quest tho.

**Comment by Kenix3** [comment]
Is it a defect that you were able to complete the quest without that NPC interaction?

**Comment by LionRsc** [comment]
No defect, was optional.
http://prntscr.com/kfvy9e

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
