### ISSUE TITLE
Grand Tree agility course sometimes stuck player. [Bug]

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#178]
**Describe the bug**
Player is unable to move & logout. (Closing client and waiting solves the problem)

**To Reproduce**
1. Go to Grand Tree
2. Do Laps at the agility course

**Expected behavior**
Get stuck (happend twice within 20 laps)

**Screenshots**
http://prntscr.com/kfqedo
Getting stuck same place.

**Comment by LionRsc** [comment]
I think it has something to do with using the net to the east.
http://prntscr.com/kfrm54
(the net with a gnome in front of him)

**Comment by Christofosho** [comment]
Moved main content to #268
