### ISSUE TITLE
Implement Mage Arena Miniquest

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#20]
When can you cast charge?
What are the messages when trying to cast the God Spells without the correct god staff?
What are the messages when trying to cast the God Spells with the staff while outside of the Mage Arena before fully completing the quests?

implement mage arena ... messages for this ... mage arena portal exact goto location
implement mage arena portal ... ObjectAction.handleWalkThrough

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
