### ISSUE TITLE
NPC and Character Clipping when Camera Pans South (Tutorial Island LONGTABLE)

### ISSUE THREAD

**Issue by Godric777-OpenRSC** [Open-RSC/Game#206]
The Cooking Instructor NPCs and Character Model (really any human model) clip with the **longtable** when the camera pans on the southern axis (effect diminishes when moving east or west).

Obviously, any character model should not clip with any isometric objects depending on what direction the camera is panned towards.

![java_2018-08-08_00-48-30 cooking tutorial island bug 1](https://user-images.githubusercontent.com/42197197/43817323-d90599e8-9aa6-11e8-9fd5-b3067189caff.png)
![java_2018-08-08_00-58-55 cooking tutorial island bug 1a](https://user-images.githubusercontent.com/42197197/43817324-d9127ef6-9aa6-11e8-8c39-db39ea0ed8ff.png)
![java_2018-08-08_00-58-58 cooking tutorial island bug 1b](https://user-images.githubusercontent.com/42197197/43817325-d91f55e0-9aa6-11e8-9d3a-9facab644b63.png)

***CLIPPING THAT IS NOT FROM THE CAMERA PAN SOUTH***
![java_2018-08-08_01-19-40 tutorial island bug 2](https://user-images.githubusercontent.com/42197197/43817871-c1a87c04-9aa9-11e8-8843-d4984d4e975a.png)
Fishing Instructor Room of Tutorial Island

**Comment by Marwolf** [comment]
Known glitch in real RSC.

Cannot fix.

https://runescapeclassic.wikia.com/wiki/Glitch?file=Tutorial_island5.png
