### ISSUE TITLE
Firemaking - Burning Logs gives incorrect EXP [Bug]

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#218]
**Describe the bug**
Burning logs at lvl 1 gives 8 exp should give 26,75 by using the following formular from wiki:
Burning normal logs should give follow exp: 25+(level∗1.75)

**To Reproduce**
Burn a log

**Comment by Christofosho** [comment]
fixed in #224

**Comment by TemperGrace** [comment]
This appears to not have been fixed.

**Comment by ipkpjersi** [comment]
Hi,

The fix is on the development server. It should be on the live server after the Sunday update.

Cheers.
