### ISSUE TITLE
Add a way to differentiate between dev and live server

### ISSUE THREAD

**Issue by ipkpjersi** [Open-RSC/Game#219]
**Is your feature request related to a problem? Please describe.**
Right now, as far as I can tell, there's not really any easy way to differentiate between the dev and live server.

**Describe the solution you'd like**
I would like a way to be able to easily differentiate between the live and dev server. There could be some red text on screen at all times saying "dev server" as well as a different title for the client itself - as well as possibly using a different cache folder for the live and dev server? I am open to any other suggestions about this.

**Comment by Marwolf** [comment]
Fixed in 84089b9a0630da08cf0f205735159f3c29c8c611
