### ISSUE TITLE
Fix Sound

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#22]
jre9 doesn't include AudioPlayer. How can we include the AudioLibrary with client distribution OR force the client to use jre8 and alert if JRE9 or JRE10 only installed on host.

**Comment by Marwolf** [comment]
Need to force client to use JRE8 and alert if JRE9 or JRE10 only installed on host

**Comment by Marwolf** [comment]
Disabled audioplayer in client until it becomes possible to implement a new sound player that is compatible with Java 9+.

**Comment by Godric777-OpenRSC** [comment]
Issue is not resolved.

**Comment by Marwolf** [comment]
I'll re-open this instead of a wontfix. Hopefully someone with magic powers can figure out a non-depreciated way of having sounds play.

**Comment by Tessalicious** [comment]
The easiest way would be to convert all sounds to .wav files or something (would also allow adding new custom sounds easier) and use javax AudioSystem to play those.

**Comment by Marwolf** [comment]
Would this increase the size of the cache by a significant amount? MP3 could be a bit easier. RSCA's client had a MP3 player.
