### ISSUE TITLE
Lava Maze issues

### ISSUE THREAD

**Issue by FalseImprint** [Open-RSC/Game#229]
**Describe the bug**
There are misplaced and missing item spawns in the lava maze. The black knights do not aggro you and can walk through the lava. Some webs are missing. 

**To Reproduce**
1. Go to lava maze
2. missing the webs near the beginning, and on the westernmost path where the giants are. 
3. Earth staff next to the steel platebody, but should be behind the tree on the easternmost path where the giants are. 
4. missing a coin spawn in the middle path behind the tree. 

**Expected behavior**

**Screenshots**
Where the items should be placed
![capture](https://user-images.githubusercontent.com/42254783/43930484-af485ab6-9c07-11e8-9380-9628d26cdec3.PNG)

Screenshots of them in official RSC
![firefox_2018-08-09_19-00-29](https://user-images.githubusercontent.com/42254783/43930277-93ae3d4e-9c06-11e8-8620-f69324a8d431.png)

![firefox_2018-08-09_18-44-49](https://user-images.githubusercontent.com/42254783/43930284-9e4c10be-9c06-11e8-832c-f556ef73ce4d.png)

![firefox_2018-08-09_19-03-01](https://user-images.githubusercontent.com/42254783/43930331-d983f142-9c06-11e8-9b53-f36f983f1a0d.png)

![firefox_2018-08-09_19-02-00](https://user-images.githubusercontent.com/42254783/43930302-b45c45e0-9c06-11e8-8e49-8edd532e8c88.png)

![firefox_2018-08-09_19-04-45](https://user-images.githubusercontent.com/42254783/43930388-19dd6e12-9c07-11e8-8f70-fd145260b6fe.png)

![firefox_2018-08-09_19-07-12](https://user-images.githubusercontent.com/42254783/43930445-6fdd561a-9c07-11e8-9290-d89b1a681a5a.png)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Christofosho** [comment]
This is all good in v2
