### ISSUE TITLE
Master Crafter Dialogue

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#240]
**Describe the bug**
The Master Crafter needs their original dialogue.

**To Reproduce**
1. Go to the crafting guild.
2. Talk to the Master Crafter.
3. He should not be a certer.

**Expected behavior**
His conversation should say:
Hello welcome to the Crafter's guild
Accomplished crafters from all over the land come here
All to use our top notch workshops

**Work to do**
Need to make him NOT a certer, and then give him the conversation.

**Comment by Fefect** [comment]
Solved in c2f62b9
