### ISSUE TITLE
Missing NPC [Stankers] at Coal Trucks/Seers

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#246]
**Describe the bug**
Picture of him missing:
http://prntscr.com/kh050i
Missing NPC, he needs to give Poison chalice to players speaking to him when at the coal mining area.
http://runescapeclassic.wikia.com/wiki/Stankers
http://runescapeclassic.wikia.com/wiki/Poison_chalice

**Screenshots**
Picture of his locations:
http://prntscr.com/kh03fd
http://prntscr.com/kh03o6

**Comment by Christofosho** [comment]
Good in v2
