### ISSUE TITLE
Update Commands in CommandHandler.java

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#25]
---------------------------------
Command Changes
---------------------------------
- (x) Document commands
- (x) Should always show commands syntax when not enough arguments supplied instead of silent fail.
- (x) Add confirmation text when command is successfully executed.
- (x) Show character edit/design menu ... change appearance ... admins/devs only
- (x) Refreshwoodcut needs to be fixed
- (x) Skip Tutorial command teleports to Lumbridge. Examine the free items.
- (x) refresh other definitions
- (x) command to go invulnerable ... accepts user .. if no user then current player
- (x) command to set current hits
- (x) admins can return from tpto .. return command can work on staff ... tpto sets a return point for the staff member. 
- (x) Summon command won't summon someone with a return point already set.
- (x) summonall and returnall ignore staff.
- (x) ::online should show staff name
- (x) ::global, ::dueling, ::muted and other state changing commands should all log.
- (x) ::jail, ::release, ::summon, ::return should all log.
- (x) item command needs confirmation
- (x) command to check staff level of player
- (x) add view inventory command of other player (admin only)
- (x) add view bank command of other player (admin only)
- (x) Command to set a player's operator level. Should report new level back to client AND write to DB.
- (x) merge with RSCL commands. Provide aliases present in rscl

**Comment by Kenix3** [comment]
#14 has history for moderator commands

**Comment by Kenix3** [comment]
------------------------
OpenRSC Commands
------------------------

------------------------
Admin Commands
------------------------
- coords
  - Usage: ::coords
  - Shows the player's current world coordinates
- online
  - Usage: ::online
  - Lists the players who are currently online.

------------------------
Developer Commands
------------------------
- coords
  - Usage: ::coords
  - Shows the player's current world coordinates
  
------------------------
Event Commands
------------------------

------------------------
Moderator Commands
------------------------
- coords
  - Usage: ::coords
  - Shows the player's current world coordinates
- online
  - Usage: ::online
  - Lists the players who are currently online.

------------------------
User Commands
------------------------
- wilderness


------------------------
Player Groups
------------------------
- 0 - Unused
- 1 - Admin
- 2 - Mod
- 3 - Unused
- 4 - Regular Player
- 5 - Subscriber
- 6 - Developer
- 7 - Event

**Comment by Marwolf** [comment]
No further action required.

**Comment by Kenix3** [comment]
There's still a lot of stuff left to do here. May not be priority, but it is incomplete. :D
