### ISSUE TITLE
Fix Landscaping at x: 888, y: 168

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#250]
This ticket pertains to any area that needs to be landscaped. Simply comment on the issue with the coordinates that are incorrect (walls, land height, land colour) and it shall be done!

**Comment by Christofosho** [comment]
x: 888, y: 168

**Comment by Kenix3** [comment]
A new issue should be opened for each location that is incorrect. If too many get opened at once, we'll open a milestone to track that.

**Comment by Marwolf** [comment]
Need to focus on v2 for landscape fixes.
