### ISSUE TITLE
Capitalization of chat is not correct

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#265]
**Describe the bug**
It's impossible to do lowercase smiley faces in OpenRSC. In RSC, the colon does not act like a period the way it does in OpenRSC.  You are also able to do capital letters after a space character in RSC, but not in OpenRSC. And the \~007\~positional stuff doesn't work server side, only client side, and also treats capitalization wrong.
 <table style="width:100%">
  <tr>
    <th>Typed</th>
    <th>RSC</th>
    <th>OpenRSC</th>
  </tr>
  <tr>
    <td>hey :o</td>
    <td>Hey :o</td>
    <td>Hey :O</td>
  </tr>
  <tr>
    <td>H E Y</td>
    <td>H E Y</td>
    <td>H e y</td>
  </tr>
  <tr>
     <td>testing~007~Testing</td>
     <td>Testing~007~Testing</td>
     <td>Testing 007 testing</td>
  </tr>
  <tr>
     <td>O_O</td>
     <td>O_O</td>
     <td>O o</td>
  </tr>
</table>

**Comment by Kenix3** [comment]
Taking this one so that we keep our chat fixes from early in the project.

**Comment by Kenix3** [comment]
Additionally, recent clients don't translate "%" into a line break like 202 does. See #139

**Comment by Hubcapp** [comment]
also can't type a circumflex mark (^)

**Comment by Hubcapp** [comment]
also can't type > or <
