### ISSUE TITLE
"You need a mining level of xx to mine this rock." is probably made up

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#269]
**Describe the bug**
I'm pretty sure this message should not be a thing. I have a recording of myself mining various rocks (mithril, addy, runite) in RSC, even without the mining level required. I even have a recording of myself getting a sapphire from runite, at lvl 53-ish mining!

Actual behavior should be that you only manage to scratch the rock, every time you attempt. and sometimes you can get gems.

**Comment by Tessalicious** [comment]
Would it be possible to upload these recordings? For archive purposes

**Comment by Hubcapp** [comment]
From the preservation discord @Tessalicious 

- http://rsc-preservation.xyz/ replays: https://cdn.discordapp.com/attachments/457163739716911120/472165100879478784/rsc-preservation.xyz_7.26.2018_4.53PM_CST.zip
- RSC 2001's replays: https://mega.nz/#!mfRl0Coa!SjsljNNoOH5z71R3ZsycDnfom6mNfFlxKcNsGlAOpDI
- Logg's replays: https://mega.nz/#!8wQ1TI7L!OgSZ99ZiMSjnPM_mnNB2jl072_9bNMx3PLWNGDKZW5U
- luis's replays: https://mega.nz/#!WfxnnBoI!gB9reiVuZ2BwVENsiIws3Ygtlv3OQGv6XOmwjgbc6uk
- shaun's replays (labelled): https://logg.biz/tylerbeg/ShaunDreclin%27s%20RSC+%20Quest%20Recordings%20labeled.zip
- kenix's replays: https://cdn.discordapp.com/attachments/457163739716911120/476467139591667712/Kenix_-_Ranged_EXP_on_Logout.rar
- jlun's replays: https://cdn.discordapp.com/attachments/457098222230306817/476080635639758848/cats.zip  https://cdn.discordapp.com/attachments/457098222230306817/476081261547618304/last_day.zip
- berry pi's replays: https://drive.google.com/file/d/1qpklCgmH7UtCsx92QrNQlNGANZ1a1A1v/view?usp=sharing

**Comment by Tessalicious** [comment]
Fixed in LIVE
