### ISSUE TITLE
Update code and data that is not used.

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#27]
-----------------------------------------
Player.isBlackarm and Player.isPhoenix are both not used.
-----------------------------------------

The player being blackarm or phoenix are checked by the completion of a dummy quest to join either gang.

Remove the fields from the Player and DB OR change quest checking to check the player instead. Would also need to save blackarm/phoenix state.

-----------------------------------------
WoodcutEvent class isn't used.
-----------------------------------------
Woodcutting is handled in the ObjectAction handler. Either remove the woodcut event or recode the ObjectAction handler to use the woodcut event.

-----------------------------------------
Prayer.itemUsed isn't used.
-----------------------------------------
Code is for giving exp for burying bones. That is handled by InvActionHandler.bury

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
