### ISSUE TITLE
Client makes OpenRSC folder in my home directory, is not portable

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#271]
**Describe the bug**
A folder was created at `~/OpenRSC` with a bunch of client stuff in it. This is annoying if I wanted to not have it there. If I move it somewhere else, then run the jar, it complains it can't find the resource it wants.

**Comment by Marwolf** [comment]
This is expected and will never change.

**Comment by Marwolf** [comment]
What is a use case for why this should be stored elsewhere?

**Comment by Marwolf** [comment]
Jagex has always stored the cache folder in the user's home folder.

**Comment by Hubcapp** [comment]
Some programs use `~/My Games` which you might consider. Or maybe you want to hijack ~/jagexcache :p

It's just for organization, to keep the home folder relatively clean. Most programs don't require the non-hidden folders in the home directory. I would like it if the program used relative paths instead of absolute paths.

**Comment by ipkpjersi** [comment]
I'm not really seeing the benefit of this. I don't even have a `~/My Games` folder so it would still be a new folder either way. Other servers also store their cache as a folder in the home path as well.

**Comment by Hubcapp** [comment]
One benefit to using relative paths instead of absolute is that you could put it on a thumbdrive and not have to install the client to play it on a computer.

The other benefit is just organization.

I think `~/My Games` might be a gnome-ism. Or it might have come from Steam.

**Comment by Marwolf** [comment]
You may want to compile your own version of the game client with the cache path set to ./

For most, the cache should be invisible and only updated by the launcher.

**Comment by Kenix3** [comment]
There is merit to releasing an official client that is portable. It may not be a priority, but should stay on our list.

**Comment by Marwolf** [comment]
Done in 1ef412420db7d736f89fafa6cddbaf0ad4e725da
