### ISSUE TITLE
Shops needs to decrease/increase in price depending on stock

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#276]
**Describe the bug**
Able to sell&Buy any amount from shops without increase/decrease in price.
Most notice-able will be selling smithed items (such as plate bodies).
Buying from shops with high quantities.

I tried checking all the issues and did not find one for this bug yet. If it has already been reported I'm sorry.

**Comment by Marwolf** [comment]
Lets rely on #310 for this.
