### ISSUE TITLE
Can't take item from 1 tile away

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#277]
**Describe the bug**
Ah, sorry #260 was duplicate. :p but looking at the code, that condition won't suffice.

You must check if you can path to the item. If you can, the current code works :+1: 

If you can't path to the item, you must check if it within 1 square of the player. I think it can go diagonal too (if player cannot path adjacent), but I'm not sure. I know for a fact you can mine ores diagonally if can't path adjacent, and you can go up ladders diagonally if can't path adjacent (and there's an obstacle in the way), so being able to pick up items diagonally if can't path adjacent would make sense to me.

To test proper behavior, there is a bronze pickaxe on a table in barbarian village which the current item-pickup logic doesn't allow the player to pick up.

**Comment by Kenix3** [comment]
I'll look at it.
