### ISSUE TITLE
Fletching items aren't made one at a time

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#279]
**Describe the bug**
In RSC, when you use feathers on dart tips, or feathers on arrow shafts, or arrow heads or headless arrow shafts, the two items are combined one at a time (they give xp drops on each combination, the fatigue drops come in "sometimes" depending on when the client-side fatigue lines up with the more precise server-side fatigue)

In OpenRSC, they are just completed up to 10 at once, all combined at the same time.

**Comment by Christofosho** [comment]
Fixed in #290
