### ISSUE TITLE
static spawned items unable to be picked up

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#293]
Submitted by Discord user: zerstoror

ones that i have confirmed so far include the varrock skirt, lumbridge pot, jug, mind, and wind rune, and iron dagger. this is not to say all items cannot be picked up as i did collect the boots inside lumbridge castle without issue. both left clicking and right click contextual menu do not pick up items. most of these i did pick up yesterday no problem. also doesnt seem to be affecting everyone.

**Comment by Hubcapp** [comment]
duplicate of #277
