### ISSUE TITLE
Draynor Manor lever puzzle

### ISSUE THREAD

**Issue by FalseImprint** [Open-RSC/Game#301]
**Describe the bug**
In the basement where you get the oil can in draynor manor for Earnest the Chicken, none of the levers do anything. You can just walk down and get the oil can without having to solve the lever puzzle. In addition, there is a wall with no Examine text in there. I do not know what it is supposed to say.

![java_2018-08-12_11-14-15](https://user-images.githubusercontent.com/42254783/44003487-3eb1cbfe-9e21-11e8-9232-21629bf9b4b7.png)

**Comment by Tessalicious** [comment]
While watching old videos the "no examine text wall" should actually be a door like all the others

**Comment by Tessalicious** [comment]
![image](https://user-images.githubusercontent.com/42176402/44036349-87deaf64-9f4c-11e8-9437-b078698877df.png)

**Comment by Tessalicious** [comment]
![image](https://user-images.githubusercontent.com/42176402/44036559-093bb7dc-9f4d-11e8-8c81-3ab6e41b8acd.png)

**Comment by Tessalicious** [comment]
Will be fixed in
https://github.com/Open-RSC/Game/pull/348
