### ISSUE TITLE
Can melee the draynor vampire from far away

### ISSUE THREAD

**Issue by FalseImprint** [Open-RSC/Game#303]
**Describe the bug**
The vampire in draynor manor can be attacked from very far away. He also spawns outside the coffin. He should not be wandering the room until you search the coffin. 

**To Reproduce**
1. Go to the vampire coffin room in draynor manor
2. attack the vampire, you will walk up to him to attack
3. after 3 rounds of combat, flee several squares away, then attack him again
4. You will attack him without having to walk up to him.

While doing the quest there was one point where the vampire had walked through the wall into the blackness and i was still able to attack him because of this. 

**Expected behavior**
You should have to walk up to the vampire each time. 

**Screenshots**
Can't get a screenshot of this one as I have already finished the quest. It won't let me attack him again.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
