### ISSUE TITLE
Agility shortcut in falador gives no xp

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#304]
**Describe the bug**
lvl 5 short cut(Handholds) at Falador West (one way only) should give 12.5 xp.
currently giving zero xp. 
I have no tested any other shortcut, I will comment when I do it might be all shortcuts is missing xp.

http://prntscr.com/khpd1l
http://runescapeclassic.wikia.com/wiki/Agility

**Comment by Christofosho** [comment]
Working in v2
