### ISSUE TITLE
Shop Prices do not update with stock changes.

### ISSUE THREAD

**Issue by InvasionSurvivor** [Open-RSC/Game#310]
Darius Verus in the discord dev channel has proposed code based off studying RSC videos and replays

![image](https://user-images.githubusercontent.com/42326426/44007024-a4b4a8c2-9e53-11e8-973c-af211c04ef04.png)

It's important to note that offset is directional. If I buy an item, price should increase.

**Comment by Christofosho** [comment]
It should be noted that the buy price can continue to decrease, even if the sell price has hit its floor. Example:
30 stock: buy 64, sell 16
59 stock: buy 48, sell 16

**Comment by Christofosho** [comment]
The closest model to being correct (selling 30 for 740gp) is:
64+59+54+49+44+
39+34+29+24+19+
16+16+16+16+16+
16+16+16+16+16+
16+16+16+16+16+
16+16+16+16+16
= 735

**Comment by InvasionSurvivor** [comment]
^ This is accounted for with the first if statement in both functions. Rough estimate states that they are decrease to 30% and 25% value respectively to buy and sell.

**Comment by Christofosho** [comment]
Related to #276

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
