### ISSUE TITLE
Valaine's Shop of Champions has incorrect prices

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#317]
**Describe the bug**
Found in the champions guild.
Has purple cape instead of Blue, and cost 32 gp instead of 41 gp.
Large black helm cost 1056 gp instead of 1,372 gp.
Black plate mail legs cost 1920 gp instead of 2496 gp.
Addamanttie plate mail body cost 12800 gp instad of 16640 gp.
http://runescapeclassic.wikia.com/wiki/Valaine%27s_Shop_of_Champions

**Comment by Kenix3** [comment]
Verify this with a replay.

**Comment by Christofosho** [comment]
#365

**Comment by LionRsc** [comment]
Shop still has same incorrect prices, I took my time looking for a replay here it is:
https://youtu.be/KK9cap-hHSs?t=7m1s
