### ISSUE TITLE
Client Message On Multi Logging

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#318]
**Describe the bug**
When trying to log into the same char on two clients, the message "You may only login to one character at a time" is displayed.

**To Reproduce**
login on one char, try to login on same char on different client.

**Expected behavior**
Maybe it can tell us exactly how many chars we can have at once, or that you can't login twice on the same char.

**Comment by Kenix3** [comment]
It should say something more to the effect of "You can only log into the same character twice.

**Comment by Marwolf** [comment]
Issue won't exist in v2.
