### ISSUE TITLE
Elvarg missing prayer drain ability

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#322]
**Describe the bug**
Elvarg is supposed to drain prayer, I don't know the details of his ability. Here is wiki:
"Elvarg can deal up to 50 damage using her fire breath, which can also drain prayer"
http://runescapeclassic.wikia.com/wiki/Dragon_(Dragon_Slayer)

**Screenshots/Clip**
https://youtu.be/M6e8ZxfUZAk?t=13m50s

**Comment by LionRsc** [comment]
Also missing the xp reward, but it is known that quest don't give proper xp yet.

**Comment by lmsv-mx123** [comment]
https://runescapeclassic.wikia.com/wiki/Dragon_Slayer
Also the message on quest completion should be "Well done..." and potion drinking should not generate bubbles.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
