### ISSUE TITLE
Silo village dose not have Gem Rocks

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#332]
Small note many quest area that is not implemented yet gives full access to their area.
http://prntscr.com/kijfio
These rocks are supposed to be gem rocks, but are silver instead.
The icon for gem stone(purple) where used under edgevill in an attempt to add rune crafting. (Those rocks where removed in last update just thinking that gem rocks might not work as inteted or are labeled as rune essence)

**Comment by Christofosho** [comment]
they exist in v2
