### ISSUE TITLE
Wayne Chains in Falador missing adamantite chain mail

### ISSUE THREAD

**Issue by Tessalicious** [Open-RSC/Game#333]
Original RSC:
![image](https://user-images.githubusercontent.com/42176402/44100838-e490b9d0-a020-11e8-89cd-350ae3e29b0e.png)

**Comment by Kenix3** [comment]
Verify this with a replay before working on it.

**Comment by Tessalicious** [comment]
Not a video but this also reports it having there
https://www.tip.it/runescape/classic/view/falador.html

**Comment by Tessalicious** [comment]
https://youtu.be/48BkDXzRxZ4?t=355
(at 5:55)
Unconfirmed if it's the real rsc but I have no reason to doubt it isn't

**Comment by Christofosho** [comment]
Yeah RSC def. had it. I remember buying it when I got myself PKed and had no cash! :)

**Comment by Christofosho** [comment]
#366
