### ISSUE TITLE
Herblaw

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#339]
Submitted by Discord user: Camel Poo

The Quest "Druidic Circle" cannot be completed, because Sanfew cannot be accessed who is on 2nd floor of Herblaw store in Taverley. This quest gives users 3 points in Herblaw, so that they may start to do potions or identifying herbs. Add 2nd floor to Taverley store and add Sanfew to it.

**Comment by Fefect** [comment]
Currently live in the dev version of the game: cee8884
Resolved
