### ISSUE TITLE
Implement authentic skill batching behaviour

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#354]
On left click, only mining should be batched.

Implement a new setting to allow the user to batch on right click menu either until resource is exhausted and/or success OR until inventory is full.

See also: #316, #320

**Comment by Christofosho** [comment]
Skill batching exists in v2, and needs to be configured to make it authentic.

**Comment by Christofosho** [comment]
Looks like I did this previously, without remembering. Closing.
