### ISSUE TITLE
Verify Christmas Cracker is Implemented Correctly

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#36]
- Christmas Cracker gives a bubble above the instigating player's head.
- If someone has a full inventory then the item(s) is dropped
- Christmas Cracker pull messages
- Different party hat colours actually have different chances of spawning.

-------------------
Below is the newer version that was changed at some point.
-------------------
- one player gets phat, the other gets a random tradable item up to rune platebody

You pull the cracker with <Player>...
<Player> is pulling a cracker with you...
Out comes a <item>!     <---- when you get a party hat
Player got the <contents>!   <---- when other player gets a party hat

-------------------
Below is the newer version that was changed at some point.
-------------------

- prize is party hat and random limited item
- other player gets nothing

You pull a christmas cracker
You get the prize from the cracker

You pull a christmas cracker
The person you pull the cracker with gets the prize

---------------------------
https://www.youtube.com/watch?v=lAudN2ui_iE

https://www.youtube.com/watch?v=aHIGZDxd7eg

http://runescapeclassic.wikia.com/wiki/Christmas_cracker

https://www.youtube.com/watch?v=XuwnA_WSM-0

Chocolate Slice must have been changed to chocolate cake in the transition from RSC -> RS2
http://www.saunalahti.fi/sniper4/index.htm
http://www.saunalahti.fi/sniper4/pic907.png
https://web.archive.org/web/20170103170406/http://www.saunalahti.fi/sniper4/index.htm

**Comment by Marwolf** [comment]
Will re-evaluate in v2.

**Comment by Kenix3** [comment]
This is known to be wrong in v2

**Comment by Christofosho** [comment]
Checked code - Looks like they give a phat to one player and do not give an additional item to anyone.

**Comment by Kenix3** [comment]
Reopening to test as the most recent description of what the code does is inaccurate to authentic.
Additionally, there are no commits that reference this issue.
