### ISSUE TITLE
Zamorak Robes has incorrect stats

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#370]
**Zamorak Top**(Ingame name is "Robe of Zamorak"): 
Has 6 Prayer bonus and no magic
http://runescapeclassic.wikia.com/wiki/Robe_of_Zamorak_(top)
Suppoed to have 3 Prayer and 5 magic.

**Zamorak Bottom**(Ingame name is "Robe of Zamorak"):
Has 5 Prayer bonus and no magic
http://runescapeclassic.wikia.com/wiki/Robe_of_Zamorak_(bottom)
Suppoed to have 3 Prayer and 5 magic.

My stats when equipped set (remember you have a baseline of 1 of each stat):
http://prntscr.com/kjbwr2

**Comment by Christofosho** [comment]
Working in v2
