### ISSUE TITLE
NPC disapear from combat and instant respawn/teleport with full health

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#374]
https://www.youtube.com/watch?v=yosH759bqUk
Fighting a black demon, when suddenly he disapear(I'm in combat against invisable/no npc) and and instant respawn/or are fulled healed a few tiles away.
There is only 3 demons in that area.
You can see I check the health off all 3 demons by changing target of my spells.

Here is some wild guesses I could come up with:
(Does NPC despawn? What happens when NPC is to far away from his area?)
Ive killed a lot of demons over the couple last day and this is first time it happens after the server was updated, it might just be very rare or maybe the change in f2p > p2p or teleport in wildness did something.

I think it is a rare occurrence, if anyone experience similar please comment.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
