### ISSUE TITLE
Unicorn drops

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#391]
Submitted by Discord user: Camel Poo

Sometimes when killing a unicorn, they drop cow hide. I killed maybe 200 unicorns, 99% the time the item drop is unicorn horn and bones, but few times they dropped off Cow Hide and bones. This happened in the north of Catherby  Unicorn spawns. A bug of some sorts?

**Comment by Kenix3** [comment]
Verify this with the wiki and/or preservation replays before working on it.

**Comment by Christofosho** [comment]
Works fine in v2
