### ISSUE TITLE
arrow shafts

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#394]
Submitted by Discord user: flying sno

I am making 10 arrow shafts per log, but only receiving 3 fletching exp per log.

**Comment by Kenix3** [comment]
Verify against replays and/or wiki.

**Comment by LionRsc** [comment]
Gives 2.5exp instead of 5exp.

Use knife on log.
Make Arrow Shafts
http://prntscr.com/klj7zl
http://runescapeclassic.wikia.com/wiki/Fletching#Arrows
https://github.com/Open-RSC/Game/issues/452

**Comment by Christofosho** [comment]
Works in v2
