### ISSUE TITLE
Fletching Longbow

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#395]
Submitted by Discord user: flying sno

When you attempt to fletch a longbow at level 1 it says level 40 is required

**Comment by Kenix3** [comment]
Verify against replays and/or the wiki before working on this.

**Comment by LionRsc** [comment]
It does give that message, the correct level would be 10.
http://runescapeclassic.wikia.com/wiki/Fletching#Bows

**Comment by Christofosho** [comment]
works in v2
