### ISSUE TITLE
Typo on tutorial island

### ISSUE THREAD

**Issue by dginovker** [Open-RSC/Game#398]
![image](https://user-images.githubusercontent.com/32943174/44301986-b6f18d80-a2ee-11e8-8f8b-03c10b915c77.png)

"Speak to the combat instructor for furhrer instructions".

**Comment by Kenix3** [comment]
Verify that this wasn't present in the official game before working on this.

**Comment by dginovker** [comment]
I'll close the issue until then

**Comment by Kenix3** [comment]
Please don't :). It may be a typo not present in authentic.

**Comment by Christofosho** [comment]
Turns out this entire message (the white text) is completely wrong! Gotta love replays.
