### ISSUE TITLE
strange forest between draynor and port sarim

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#404]
Submitted by Discord user: flying sno

on the northwest side of draynor bank there is a bunch of trees all the way to the wall between port sarim and draynor. Not there in rsc

**Comment by Kenix3** [comment]
Verify object placement with Logg's world tour replays.

**Comment by Marwolf** [comment]
<img width="1032" alt="screen shot 2018-08-19 at 21 57 25" src="https://user-images.githubusercontent.com/16737510/44316686-e1c90800-a3fa-11e8-9013-26bceae5eecb.png">

Need to verify with replay.

**Comment by Marwolf** [comment]
Not in v2.
