### ISSUE TITLE
scorpion on karamja

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#405]
Submitted by Discord user: flying sno

When you run from a scorpion on karamja near volcano it will run diagonal away from you and then catch up to you even if you were running away the entire time.

**Comment by Hubcapp** [comment]
May be kosher. They're pretty relentless

**Comment by Kenix3** [comment]
Verify aggressive behaviour in replays.

**Comment by Marwolf** [comment]
Not an issue in v2.
