### ISSUE TITLE
Imps on Karamja walk on water

### ISSUE THREAD

**Issue by aleclashamtaylor** [Open-RSC/Game#408]
<img width="624" alt="screen shot 2018-08-18 at 7 47 04 pm" src="https://user-images.githubusercontent.com/2342684/44304080-bc1b0080-a31f-11e8-9ce3-545b9c65bcd1.png">

**Comment by aleclashamtaylor** [comment]
Actually, it seems the scorpions do this as well.

**Comment by Marwolf** [comment]
v1 issue, won't exist in v2.
