### ISSUE TITLE
Ardougne cake stall bugs

### ISSUE THREAD

**Issue by aleclashamtaylor** [Open-RSC/Game#410]
It should not be possible to fail when thieving from the cake stall in Ardougne (so long as you have the level 5 thieving requirement). And when the baker alerts the guards, they don't attack the player as they should. Also, there shouldn't be an eye patch displayed while thieving.

<img width="624" alt="screen shot 2018-08-18 at 7 58 15 pm" src="https://user-images.githubusercontent.com/2342684/44304132-3f892180-a321-11e8-8360-4ef17d78ca84.png">

**Comment by Christofosho** [comment]
Working in v2
