### ISSUE TITLE
Black knights' fortress doors should close behind the player

### ISSUE THREAD

**Issue by aleclashamtaylor** [Open-RSC/Game#411]
<img width="624" alt="screen shot 2018-08-18 at 10 07 58 pm" src="https://user-images.githubusercontent.com/2342684/44304862-9cdb9d80-a336-11e8-9f3f-cb07da346315.png">
Usually these two interior doors close behind the player, and when a player opens them during the quest the black knights in the large room target the player. This is mentioned in the quest guide on the RSC wiki.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
