### ISSUE TITLE
Varrock's Gate & Guard

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#423]
Submitted by Discord user: rick ibm#1687

The Gate and Guard located behind the east bank is completely action-less when attempting to open Gate or talk to Guard.

**Comment by Christofosho** [comment]
Confirmed: Gate works, but guard does not. Dialogue can be found here:
http://runescapeclassic.wikia.com/wiki/Guard/Dialogue

**Comment by Christofosho** [comment]
Works as expected in v2 after further testing.
