### ISSUE TITLE
No Dragon Sword Shop in zanaris after Lost city quest

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#425]
Submitted by Discord user: Brion

I am not able to talk to Jakut to buy dragon longswords. When I talk to him there is no chat dialogue, hence no shop interface

**Comment by LionRsc** [comment]
http://runescapeclassic.wikia.com/wiki/Dragon_Sword_Shop

**Comment by Christofosho** [comment]
Working in v2
