### ISSUE TITLE
Fletching.

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#439]
Submitted by Discord user: Itox

Fletching Arrow shafts yields 2 instead of 5 exp

Making headless arrows (arrow shaft + feather) yields 10 experience instead of 15

and making bronze arrows yields 12 instead of 30 exp.

**Comment by LionRsc** [comment]
According to wiki, everything but the arrow shafts giving 2.5 xp is correct.
Adding feathers to headless arrows = 10 xp per 10 made.
Making bronze arrows yields 12.5 xp as wiki states.
http://runescapeclassic.wikia.com/wiki/Fletching#Arrows

**Comment by LionRsc** [comment]
Wiki **likely** incorrectly listed: "12.5 exp per 10 arrows" and should instead have been **15 exp per 10 arrows**

Wiki: 
"Players with a Fletching level of 1 can make Bronze Arrows by using Bronze Arrow Heads with Headless Arrows, yielding up to 30 Fletching experience per 10 arrows made. "
http://runescapeclassic.wikia.com/wiki/Bronze_Arrows
Tip it: 
"Making arrows shafts: 1 log = 10 shafts = 5 exp." 
"Feathering shafts: 10 feathers + 10 shafts = 10 headless arrows = 10 exp."
https://www.tip.it/runescape/classic/view/fletching.htm

Me & Itox suggest using a replay where a person adds bronze tips to headless arrows, and correct wiki accordingly. Feel free to contact me
Thanks to Itox for finding the inconsistency.
