### ISSUE TITLE
Mage arena bank is incorrect

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#443]
<img width="416" alt="screen shot 2018-08-20 at 19 25 58" src="https://user-images.githubusercontent.com/16737510/44371818-ea7b1600-a4ae-11e8-9d88-b9f0dfe78f5d.png">

Need to reference replays.

**Comment by LionRsc** [comment]
Here is a link to the correct shop stock:
http://runescapeclassic.wikia.com/wiki/Mage_Arena_Rune_Shop
