### ISSUE TITLE
There is a gate between f2p & p2p wild that isn't meant to be there

### ISSUE THREAD

**Issue by aleclashamtaylor** [Open-RSC/Game#445]
<img width="624" alt="screen shot 2018-08-20 at 7 10 58 pm" src="https://user-images.githubusercontent.com/2342684/44372875-06cd8180-a4b4-11e8-81c6-7ba148bda7c8.png">

This wasn't in RSC. It's just east of the ice giants/warriors/spiders area.

**Comment by Marwolf** [comment]
@aleclashamtaylor  Ah. I just ran through the fence line adding gates that looked to be missing. Are there any others that should not exist along the wall?

**Comment by aleclashamtaylor** [comment]
Not sure, I didn't explore the whole wall. I'll check in a little while and update this thread.

**Comment by aleclashamtaylor** [comment]
@Marwolf So there are two more gates. One above the sapphire house, and one northeast of greater demons. The one above the sapphire house should be removed, while the one northeast of greater demons should be moved west to its original location.

**Comment by Marwolf** [comment]
Gates all removed
