### ISSUE TITLE
Gnome Agility Arena - Stuck before 2nd net climb

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#449]
**Describe the bug**
Tried to climb over the eastern-most net (edit: happened again with middle net. Net may not matter). Game printed text "you take a few steps back" and character walked to middle between net and watch tower object, and appears the script is stuck. Unable to move or log out.

**To Reproduce**
Have only reproduced once. Unreliable reproducing behavior.

**Expected behavior**
Appear on the other side of the net after automatically taking a few steps back

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/44441316-f394e180-a599-11e8-96bd-c6fd368482df.png)

![image](https://user-images.githubusercontent.com/995993/44441335-05768480-a59a-11e8-8cab-b14d5d78e5d6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: OpenRSC client
 - Version: as of 8/21/2018

**Additional context**
This was during my first attempted loop around the course. (Edit: Happened again at level 15)
Unable to move, follow other player or log out. Forcing the client to close and waiting for my character to time out appears to exit the broken script.

**Comment by LionRsc** [comment]
Related to issue 178 for reference. Thanks for putting so much detail into it.
https://github.com/Open-RSC/Game/issues/178
