### ISSUE TITLE
Stuck in Taverley

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#458]
Submitted by Discord user: Bacon Attack

I am stuck on a red mat in Taverley. It is the building across from the building that has a chest in it. I clicked search door mat and it said "You find a key under the mat" Then I clicked open door. "The door won't open. You notice a black cross on the door." I cannot move off of this spot nor can I log out. I get the "Sorry, you can't logout at the moment" message. My character will not respond to anything, even inventory clicks.

**Comment by Marwolf** [comment]
<img width="499" alt="screen shot 2018-08-22 at 20 24 57" src="https://user-images.githubusercontent.com/16737510/44497834-74f77d00-a649-11e8-8380-c32876cb6080.png">

Solution: close the client and re-login. Player is set busy and not un-set.

**Comment by Christofosho** [comment]
fixed in v2
