### ISSUE TITLE
Yanille - Ye Olde Dragon Inn Bartender NPC no dialog/beer sale

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#464]
Ye Olde Dragon Inn is the only pub in the city of Yanille. It is found in the south western corner of Yanille. The pub is notable for being the only place in RuneScape Classic where players may buy the Herblaw boosting drink Greenmans ale and the Gielinor famous Dragon bitter.
http://runescapeclassic.wikia.com/wiki/Ye_Olde_Dragon_Inn

**Comment by Christofosho** [comment]
working in v2
