### ISSUE TITLE
Al-Kharid Gate

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#465]
Submitted by Discord user: Camel Poo

If you talk to the guards before passing through the Al-Kharid gate you can pay them 10gp to pass through the gate. But the gate wont open. 
Instaed, when you click on the gate they answer that you must pay 10gp entry. Only by clicking the gate you can pass. If you talk to the guards first they end up charging you money, but the gate will never open.

**Comment by Christofosho** [comment]
working in v2
