### ISSUE TITLE
Pirate hideout missing doors - Requires Lockpick & 39 Thiev to open

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#481]
Pirate hideout is located lvl 54 wildy, west of Mage Arena
Pirate hideout missing doors - Requires Lockpick & 39 Thiev to open
http://runescapeclassic.wikia.com/wiki/Pirates%27_Hideout

I would think you only need Lock pick on your way in to avoid players getting stuck after dropping their Lock Pick.

**Comment by Christofosho** [comment]
Working in v2
