### ISSUE TITLE
Shadow Spiders has no prayer drain

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#483]
Shadow spiders are large monsters which halve your remaining prayer points at the start of combat. They cannot lower your prayer below one point. 
http://runescapeclassic.wikia.com/wiki/Shadow_spider

**Comment by Christofosho** [comment]
v2 has `server/src/com/openrsc/server/event/rsc/impl/combat/scripts/all/ShadowSpiderPrayerDrain.java` which solves this.
