### ISSUE TITLE
Update code to v2.0.0

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#486]
Going to put our 2.0.0 beta TODO list here

Code Updates to Port
```
- Commands.
- Group set up. 
- Invisible and Invulnerable command rendering.
- Reload definitions commands.
```

**Comment by Christofosho** [comment]
Updated to reflect the recent changes.

**Comment by Kenix3** [comment]
- File defs to DB.
- Sound crashing
- LoginResponses to an enum (especially on registration)

Are all pushed to a subsequent update.
