### ISSUE TITLE
Implement authentic skilling chances

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#49]
Percent chance of success:

First check if you have the required level to gather this resource. If you do, continue.
min( 128, max(1, (players_skill_level) + 41 - ((resource_required_skill_level * 1.5)) ) )
Roll a die 100, on 1 fail, on 128 success.

**Comment by Marwolf** [comment]
Is this still valid?

**Comment by Kenix3** [comment]
Yes. That formula is known to be good for at least mining.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.

**Comment by Kenix3** [comment]
Will need to implement in v2

**Comment by Kenix3** [comment]
Preservation project has data on rocks mined.
Scripts were updated for WC and Fishing and determined to essentially share the same chances.
See preservation discord for data figures:
https://discord.gg/pnXkKQe
