### ISSUE TITLE
anchovies only heal 1 hp

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#490]
Submitted by Discord user: kristof

im a fucking idiot, and forgot to change anchovies to heal 3 in the def_edibles, so they only heal 1 atm.

**Comment by LionRsc** [comment]
Anchovies are supposed to heal one.
Anchovies are a type of cooked fish which can be obtained by cooking raw anchovies with at least level 1 cooking. This grants 30 cooking experience. They can be eaten to restore one hit.
http://runescapeclassic.wikia.com/wiki/Anchovies

**Comment by lmsv-mx123** [comment]
I do have a replay on many fish edible heals if that helps
