### ISSUE TITLE
Tutorial Island: Community Instructor Dialogue

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#497]
**Describe the bug**
Community Instructor gives 2 options immediately, when it should only give one. This makes the chat occur in the wrong sequence (she answers wrongly for the second option).

**Expected behavior**
She should have one option, and then the second options appears after the first option's conversation is complete.

**Comment by Marwolf** [comment]
Is this v1 or v2?

**Comment by Christofosho** [comment]
#543
