### ISSUE TITLE
Removal of Curse Words

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#498]
**Is your feature request related to a problem? Please describe.**
There are many left over swear words through the code that could be replaced with better descriptors for their use. 

**Describe the solution you'd like**
Removal / Replacement of said words.

**Comment by Marwolf** [comment]
Refactor rename to "frick"

**Comment by Christofosho** [comment]
It might be more prudent to use names that make sense, in the context of the code. I'll go through some of the more common words (ie: shit, fuck, bitch) and make the code readable.
