### ISSUE TITLE
Official RSC non-Kosher Changes

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#50]
Here is a list of the features for this release that were not in official RSC.
---------------------------
Quality of Life Improvements
---------------------------
- Bank Notes
- Use item on a banker to deposit it
- Drop X, Drop All in client
- Camera Controls
- Can craft 5 bars into arrowheads at the same time.

---------------------------
Game Additions
---------------------------
- Global Chat
- New commands. [TODO: Document exactly which ones once we have a final list of commands]
- Alert when a player uses an item on you.

---------------------------
Cosmetic non-kosher differences
---------------------------
- Thrander's plate/top armour messages do not use authentic item name capitalization. Very small message change that was easier to just use the existing item name.
- Added additional colour codes like @dgr@

---------------------------
Server Additions
---------------------------
- Adverts that display every so often. Example would be to give current players online. Can be disabled by removing adverts in conf_advert.
- There are now invulnerable and invisible players. Protocol differences to support this as well.

---------------------------
Bug Fixes
---------------------------
- Fixed issue where messages that are wrapped to another line above a player's head lose the colour code.
- [Verify this is true] Fixed issue where using certain skills and logging out before the trigger to give exp fires would give the exp to a player who logs in with your old player ID.

---------------------------
Game Differences
---------------------------
- Start with 1184 hits exp NOT 1000 as in the official game. In RSC official hits is a special case in that 1000 exp = lvl 10.
- Performing gathering skilling (mining/woodcut/fishing) now uniformly stops you at 100% fatigue. The official game had a few stopping before 100%.

---------------------------
Web Server Differences
---------------------------
- RSC back in the day used to be a java web applet. Modern browsers block these.
- Our launcher works a lot different to official RSC. See #94 for official behaviour

**Comment by Hubcapp** [comment]
Under QOL, quick bank as well

**Comment by Kenix3** [comment]
These will be enabled/disabled via settings.
