### ISSUE TITLE
Implement World Map Generator/Renderer

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#56]
This will render a world map or at least use an existing one and then render dots to display where players are on the map.

https://github.com/sean-niemann/RSC-Landscape-Generator
github.com/cath-mawr/rscmapgen

**Comment by Marwolf** [comment]
Will need to render a fresh one based on a verified clean landscape and reset the coordinates to align with the image. Also need to set canvas to refresh instead of entire page for load effiency.

**Comment by Marwolf** [comment]
Need a way to connect player avatars generated by server to website world map overlay - could use a local nginx server on the game server to remotely load over private IP avatars.
