### ISSUE TITLE
Verify correct message on gaining quest point and correct skill xp gain order

### ISSUE THREAD

**Issue by lmsv-mx123** [Open-RSC/Game#563]
**Describe the bug**
In RSC it should be "You haved gained X quest points!" instead of "You have gained X quest points!" when its more than 1, when its 1, points should be "point".
As far as the order of the skill gain order, make sure it matches as close as possible to have similar to https://runescapeclassic.wikia.com/wiki/Category:Quest_reward_images

**To Reproduce**
On quest finish, some quests display the "fixed" message of You haved ...
On quest finish some quests sent out skill gain in wrong order - for example Grand tree where its send out as agility, magic, attack while it should be agility attack and magic.

**Expected behavior**
- Correct "glitched" message on You have gained
- Correct order of skill gain

**Comment by Christofosho** [comment]
#564 for have -> haved

**Comment by Christofosho** [comment]
#683
