### ISSUE TITLE
Thrander messages are incorrect

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#57]
https://cdn.discordapp.com/attachments/457168898907832320/463781109260353546/unknown.png

**Comment by Kenix3** [comment]
NOTE that Thrander irregularly capitalizes item names. This should be logged as slightly off from real RSC kosher.

Log here what the messages SHOULD be.

**Comment by Kenix3** [comment]
Check with preservation to get exact right thrander messages

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
