### ISSUE TITLE
Ensure Quest Progress is Saved When DB Transitions

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#579]
**Describe the bug**
Transitioning to v2 from v1 might mean loss of quest progress, as both versions seem to store these differently. We need to make sure these are transitioned via a script or another method.

**Comment by Marwolf** [comment]
I've made sure that if you completed the quest, you get credit. If you haven't finished it, you just get set to stage 0 again. There are too many quests and too many custom stages to try to manage this for only a few players that this would matter for. #736
