### ISSUE TITLE
Dummy training house 

### ISSUE THREAD

**Issue by CamelPooBoy** [Open-RSC/Game#584]
A  dummy is a scenery item that can be found in Varrock, in the house just north of the east bank. Players with under level 8 attack can hit them and gain a small amount of attack experience without gaining any hits experience. Hitting a dummy should give 5 xp per hiti until level 8 attack, which you can no longer train on dummies. 
At the moment, when you hit the dummies even with level 1 attack, it says that there is nothing you can gain by hitting the dummy.

Solution: Fix the dummies to give attack experience 5xp per hit until 8 attack for authentic experience.

Also one dummy is located in Handelmort mansion in East Ardougne
http://runescapeclassic.wikia.com/wiki/Handelmort_mansion

**Comment by Christofosho** [comment]
Should be working on v2
