### ISSUE TITLE
Making Wine 

### ISSUE THREAD

**Issue by CamelPooBoy** [Open-RSC/Game#585]
At level 35 of Cooking, one should be able to do Wine by mixing Grapes with Jug of Water

>Wine can be made at level 35 Cooking by placing grapes in a jug of water giving the player 110 Cooking experience. This may fail, which results in the player receiving bad wine. The player must then wait 6 ticks (3.6 seconds) for the wine to mature, assuming that they have not failed. Once level 70 Cooking has been reached, it is no longer possible to fail maturing the wine.

http://runescapeclassic.wikia.com/wiki/Wine

Even with 35 cooking and trying to mix grapes with jug of water, it says "nothing interesting happens" thus making wine is impossible at the moment for cooking experience.

Solution: Fix the bug that allows players to do wine with Cooking 35

**Comment by Christofosho** [comment]
Working in v2 :)
