### ISSUE TITLE
Monk of Zamorak (Lv29) should always drop steel mace on death

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#609]
Submitted by Discord user: clive

Monk of Zamorak (Lv29) should always drop steel mace on death, which in this case it drops nothing instead.

**Comment by Marwolf** [comment]
Is this on the test world? If on the current live world, that code base is completely different and soon to change. Hopefully that will correct this if so.

**Comment by Christofosho** [comment]
#620
