### ISSUE TITLE
Fight Arena (Quest)-V2.0

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#614]
[Graphical Glitch]: Health bar of Bouncer (level-122 dog) and General Khazard (level-100) extends way off right going off the screen.

After fighting bouncer, message popped up about going to Lady Servil to claim my reward, even though I still needed to kill General Khazard (level-100).

**Comment by Christofosho** [comment]
This works as intended, for the quest portion. The HP bar is a larger base-wide issue we are looking in to. :)
