### ISSUE TITLE
Stackable Items: count-number [Non-Kosher] & hold to Increase/Decrease amount [Kosher] - V2.0

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#616]
Inventory:
https://cdn.discordapp.com/attachments/459699205674369027/489046589214687243/unknown.png

Examine:
https://media.discordapp.net/attachments/459699205674369027/489046977665826826/unknown.png?width=737&height=62

Bank (Partially kosher):
https://media.discordapp.net/attachments/459699205674369027/489048058433110016/unknown.png?width=309&height=146

Also, click & hold items to increase/decrease amount (just like pre-2009 players had to use this method but became optional after 2009) is not present in V2, this feature is kosher.

**Comment by multi-talented** [comment]
"Can you expand upon the "click and hold" you mentioned?"
Back in Pre-2009 RSC, the only way to trade other players with stack-able items like gp is to click and hold to a desired amount was reached. Like if another player offered a rune long sword, I have to click and hold my gp until it reached 32k gp. I haven't tested this with other players but it also worked in banks and it didn't work then.

**Comment by Christofosho** [comment]
Finished everything except click-and-hold, which is more of a feature request than a bug.

**Comment by Christofosho** [comment]
Bug again, ty for the video Rick! :)

**Comment by Christofosho** [comment]
#721
