### ISSUE TITLE
Thieving Stalls - V2.0 

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#617]
~~Baker's loot sometimes includes Slice of cake and bread = only in rs2 & rs3. [Non-Kosher]~~

After you steal from Stalls, and talk to the Merchants of that stall, they don't call on guards for help. (However in real RSC, the Baker never did.) [Non-Kosher]

Location: ardy

**Comment by Christofosho** [comment]
Fixed part one of this

**Comment by Bl0ds** [comment]
For part two:

final int[] guardID = { 65, 322, 323 };
		//Hero = 324, Knight = 322, Guard = 65, Paladin = 323.
		Npc shopkeeper = Functions.getNearestNpc(player, stall.getOwnerID(), 8);
		Npc guard = Functions.getMultipleNpcsInArea(player, 12, guardID);

**Comment by Christofosho** [comment]
#692
