### ISSUE TITLE
1 Hit Attack-able NPC's! BUG - V2.0

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#618]
Same Bug as with KBD, Fire Giants in level 52 wilderness this time. Very possible that there will be more attack-able NPC's with this bug.

**Comment by multi-talented** [comment]
List of NPC's so far:
*KBD in lair.
*Fire Giants in wild.
*Battle Mages in Mage Arena.

**Comment by Marwolf** [comment]
fire giant: npc 344 - confirmed. coords: 271, 2956
battle mage: npc 789, 790, 791 - confirmed. coords: 224, 133
red dragon: npc 201 - confirmed. coords: 240, 171
black dragon: npc 291 - confirmed. coords: 273, 3002

**Comment by Marwolf** [comment]
Fixed in #654
