### ISSUE TITLE
Not all EXP award and skill events have definitions in the database

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#62]
- Crafting Leather
- Crafting Pottery
- Crafting Glassblowing
- Crafting Holy Symbol/Unholy Symbol
- Crafting Molten Glass
- Crafting Wool
- Crafting Flax to Bow String
- Crafting Staves

- Smithing Nails
- Smithing Canonball
- Smithing Golden Bowl
- Smithing Bars into objects isn't fully data driven

- Stringing Bows

**Comment by Kenix3** [comment]
Cooking table is missing the following foods:
Ugthanki Kebab
all gnome cousine
Cooked Oomlie meat Parcel
not sure if gnome drinks are counted on this

Wiki has all data for them.

**Comment by Kenix3** [comment]
Crafting table is missing the following crafting items:
leather boots
leather gloves
leather armour
pot
pie dish
bowl
holy symbol
unholy symbol
ball of wool
bow string
molton glass
beer glass
vial
orb
all battle staves

**Comment by kInGkRiStOf** [comment]
config_table_def_edible_heals missing accurate/data:
food_id 210(kebab) missing accurate heal amount
food_id 590(lava eel) set to 14, wiki says 11-14, need accurate data, and a way to vary the heal amount
food_id 856(lemon slices) missing accurate heal amount (think it will be 2)
food_id 860(diced lemon) same (think it will be 2)
food_id 865 (lime slices) same (think it will be 2)
food_id 885 (gnome bowl) same
food_id 900 - 914 (all need accurate heals)
food_id 923 (ugthanki kebab) same
food_id 924 (special curry) unobtainable in game, still in table (set to 0)
food_id 936 (jangerberries) set to heal 2, but also has other stat effects, explore options
food_id 937-943 (all gnome drinks) not included in table, look to add them
food_id 944-957 (all gnome foods again) explore why they are in the code twice, maybe one raw, one cooked?
food_id 1086 (nightshade) should lower hp by 43%, can i turn it into a function?
food_id 1245 (edible seaweed) no accurate heal amount
food_id 1301/1302 (both added to open rsc, not in original rsc) set to 0, will delete when available

**Comment by kInGkRiStOf** [comment]
config_table_def_fish missing accurate data:
object_id | net_id | bait_id | fish_id | level | experience | id
-- | -- | -- | -- | -- | -- | --
1193 | 548 | -1 | 1192 | 85 | 115 | 19
1193 | 379 | -1 | 545 | 76 | 110 | 20
object id 1193 does not exist. item id 1192 is manta ray, 545 is shark. Zero'd out both entries.
Find object 1193 in open rsc and delete.
-- | -- | -- | -- | -- | -- | --
1190 | -1 | -1 | -1 | -1 | 0 | 29
zeor'd out object 1190, need to find in open rsc and delete.

Manta ray and turtle do not exist in table. Look into fishing trawler code to see if it is there.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_fishing
object_id | net_id | bait_id | id
-- | -- | -- | --
1193 | 548 | -1 | 9
1193 | 379 | -1 | 10
1219 | 379 | -1 | 16
1190 | 379 | -1 | 18

made these net id's -1, since all these objects are added, not kosher.
Need to delete.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_gem.csv
All clean and fixed.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_herb.csv
herb_id | potion_id | level | experience | id
933 | 934 | 76 | 60 | 11
Fixed xp, and changed guam level to 3(requires Druidic Ritual to start doing herblaw)
Added torstol to the table. I think we will have to go throughout the rest of the game, and make sure it works in other places.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_herb_second.csv
secondary_id | unfinished_id | potion_id | level | experience | id
936 | 935 | 963 | 78 | 700 | 14

added torstol and zammy pot to above.
Need to add:
Explosive Compound
Ogre Potion
Blamish Oil
Gujuo Potion

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_log_cut.csv
log | shaft_amount | shaft_level | shortbow_id | shortbow_level | shortbow_experience | longbow_id | longbow_level | longbow_experience | id
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
14 | 10 | 1 | 277 | 5 | 20 | 276 | 40 | 10 | 1
632 | 15 | 15 | 659 | 20 | 70 | 658 | 100 | 25 | 2
633 | 20 | 30 | 661 | 35 | 133 | 660 | 166 | 42 | 3
634 | 30 | 45 | 663 | 50 | 200 | 662 | 233 | 58 | 4
635 | 40 | 60 | 665 | 65 | 266 | 664 | 300 | 75 | 5
636 | 50 | 75 | 667 | 80 | 333 | 666 | 366 | 92 | 6

Problem being that all logs make shafts, and there is no shaft xp awarded. Only logs should make shafts.
Fix later.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_mining.csv
rock_id | ore_id | experience | level | respawn_time | id
-- | -- | -- | -- | -- | --
588 | 889 | 200 | 40 | 120 | 21
1194 | 890 | 200 | 40 | 120 | 22
1195 | 891 | 200 | 40 | 120 | 23
1196 | 159 | 200 | 40 | 120 | 24
1203 | 1290 | 5 | 1 | 3 | 27

The first 3 are gem rocks, forth is set to emerald, and last one is an unknown item and object. need to make gem rocks give random gems, (sapphire and emerald have the same rate, based on my 100+ days of mining only gem rocks), and delete the added item/object.
Leaving them in for now, as I'm not sure if a -1 will break the game.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_picklock_door.csv
Added door 96, 99, 100, 162
Need legends quest door, and underground pass railings object ID's
Added location column to this list, not in original file. 
door_id | level | experience | picklock_required | location
-- | -- | -- | --
0 | 39 | 35 | 1 | ?
0 | 39 | 35 | 1 | ?
0 | 39 | 35 | 1 | ?
97 | 61 | 200 | 0 | ardy castle
93 | 7 | 15 | 0 | one story east ardy
95 | 31 | 100 | 0 | ardy sewer
94 | 16 | 60 | 0 | nature chest/yan anvil
100 | 32 | 100 | 1 | axe hut
99 | 39 | 140 | 1 | pirate hut
96 | 46 | 150 | 0 | chaos druid tower
162 | 82 | 200 | 1 | yan dung

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_pickpocket.csv
All clean and fixed.

**Comment by kInGkRiStOf** [comment]
[Gnomeball + smuggle.zip](https://github.com/Open-RSC/Game/files/2237092/Gnomeball.%2B.smuggle.zip)

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_pickpocket_loot.csv
fixed data that was wrong and missing.
no good data for difference in different gnomes being thieved, so all are the same.
(check the bluberry dude for the most sever difference I'd think)

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_prayer
All clean and fixed.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_smelting.csv
All clean and fixed.
Gold smithing xp is 33.5 when wearing gold smithing gauntlets(+11xp per ore)

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_required_stats
openrsc_config_table_def_shop_items
openrsc_config_table_def_shops

none of these have been changed yet.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_smithing.csv
- fixed some levels, found a bunch of stuff not kosher(pickaxe and 50 arrowheads at a time)
- need to add steel nails, and cannon balls
- items to remove:
level | bars | item_id | amount | id |  
-- | -- | -- | -- | -- | --
1 | 1 | 156 | 1 | 8 | pickaxe
18 | 5 | 669 | 50 | 20 | 50 arrowheads 
16 | 1 | 1258 | 1 | 29 | pickaxe
33 | 5 | 670 | 50 | 41 | 50 arrowheads
31 | 1 | 1259 | 1 | 50 | pickaxe
48 | 5 | 671 | 50 | 62 | 50 arrowheads
51 | 1 | 1260 | 1 | 71 | pickaxe
68 | 5 | 672 | 50 | 83 | 50 arrowheads
71 | 1 | 1261 | 1 | 92 | pickaxe
88 | 5 | 673 | 50 | 104 | 50 arrowheads
86 | 2 | 1262 | 1 | 113 | pickaxe
99 | 5 | 674 | 50 | 125 | 50 arrowheads

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_spell_aggressive.csv
- Cannot confirm data in this table. Leaving it as is.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_stall_loot.csv
- added regular fur to fur stall
- added rock cake stalls, with loot. Need to verify which stall id(999, 1034) is actually in rsc

stall_id | item_id | item_amount
-- | -- | --
999 | 1061 | 1
1034 | 1061 | 1

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_stall_guardian.csv
_ need to go thieve until I kill all everything that guardians these stalls.

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_unidentified_herb.csv
- Added torstol.
- Changed xp for jungle potion herbs to 0, until someone can confirm there is xp from them.

unidentified_id | identified_id | level | experience | id
-- | -- | -- | -- | --
815 | 816 | 3 | 0 | 12
817 | 818 | 3 | 0 | 13
819 | 820 | 3 | 0 | 14
821 | 822 | 3 | 0 | 15
823 | 824 | 3 | 0 | 16
933 | 934 | 76 | 60 | 17

**Comment by kInGkRiStOf** [comment]
openrsc_config_table_def_woodcut.csv
- all clean and fixed

**Comment by lmsv-mx123** [comment]
hey on the "Gold smithing xp is 33.5 when wearing gold smithing gauntlets(+11xp per ore)" it should be 33.75, this at the end of my family crest replay @kInGkRiStOf @Kenix3

**Comment by lmsv-mx123** [comment]
Smithing rune table requirements need cleanup, the correct requirements are in the wikia table

**Comment by Marwolf** [comment]
Has Kris's csv file been implemented in the SQL file?

**Comment by Kenix3** [comment]
Yes, it should have been closed. There are some hold over issues, but we'll work on them independently of this.
