### ISSUE TITLE
Mining Guild Botters

### ISSUE THREAD

**Issue by CamelPooBoy** [Open-RSC/Game#621]
![botters](https://user-images.githubusercontent.com/43058162/45424988-c3c09180-b6a0-11e8-98f0-e3524deecae9.jpg)

All 3 guys mine the same rocks, probably use same accout, as long as you enter chat window or call them out. They exit the mine. Most probably 3 accounts used by the very same guy. Very shitty botters and they are doing it 100%, I have reported them but the activity continues and botting goes on in the mining guild.

**Comment by dginovker** [comment]
Is botting not allowed on the official server?

**Comment by Zephedge** [comment]
![image](https://user-images.githubusercontent.com/995993/46190293-0600ea00-c2c1-11e8-9cf9-7938ec464f7c.png)

Bots have moved to mine south of lumbridge

**Comment by Marwolf** [comment]
If they are caught in v2, they will be fully banned.
