### ISSUE TITLE
Sleep words are not loaded.

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#63]
Sleeping causes a server crash.

**Comment by Marwolf** [comment]
Need to test locally to see if actually is a bug.

**Comment by Kenix3** [comment]
This doesn't appear to be limited to admins.

**Comment by Marwolf** [comment]
Sleepwords dont show if enabled but the server no longer crashes. If sleep words are enabled, the esc key gets out of sleep screen.
