### ISSUE TITLE
Smelting Bug

### ISSUE THREAD

**Issue by CamelPooBoy** [Open-RSC/Game#635]
This happens only with ores that require Coal to Smelt them to bars.
Here is my inventory with 6 Mithril Ores and 23 Coal ores. To smith 6 Mithril bars I should require 24 coal ores ( 6 mithril x 4 Coal )
![smithing](https://user-images.githubusercontent.com/43058162/45476136-dab9bf00-b746-11e8-8768-5f3f5108974b.jpg)

On the left you can see 23 ores with 6 ores. I should end up with 5 mithril bars, instead, If I am fast enough by clicking speed: I can smith 6 bars with only 23 ores, instead of with 24 ores required.

This same bug happens with Steel bars too, it does not always work, but if one is "fast enough" by clicking the bars to furnace: this seems to happen. If I insert the ores to furnace slowly this bug does not happen and everything is normal.

Solution: Fix the bug that allows you to smith more bars than you are supposed to with less coal than required.

**Comment by Marwolf** [comment]
Is this on the dev test world that is running the v2.0.0 code? If it is on the regular one, everything is a different source and to change.

**Comment by Marwolf** [comment]
We need to keep only issues for the new code base in here for tracking.
