### ISSUE TITLE
Cat item behaviours

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#64]
Using a cat on a level 2 rat gives the message
   the cat pounces on the rat... 
    ...and quickly gobbles it up it returns to your satchel licking it's paws

Picking up a second cat has this message
    "it's not very nice to squeeze one cat into a satchel 
    ...two's just plain cruel!" 

http://runescapeclassic.wikia.com/wiki/Cat

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
