### ISSUE TITLE
"Talking to" Gertrude doesn't start conversation

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#644]
Submitted by Discord user: Slauvy#7861

Can't do Gertrude's Cat because she's refusing to speak to me, I've tried to relog and remove my armor/weapons hoping for the best but nothing seems to work.

**Comment by Christofosho** [comment]
Hey there,
Was this found on the live server, or the dev server?

**Comment by Marwolf** [comment]
Unfortunately everything in the live v1 code is soon to be replaced and we aren't doing any more code changes to it as we are spending all of our time getting v2 ready. The server source is completely different and this should hopefully not be an issue on v2.
