### ISSUE TITLE
Essential NPCs missing from The Hazeel Cult quest

### ISSUE THREAD

**Issue by Slauvy** [Open-RSC/Game#652]
These issues are on the live server.

The Carnillean house southwest of King Lathas's castle located in the western side of East Ardougne is missing some essential NPCs to start, progress, and complete the Hazeel Cult quest. The guards are posted outside the home (intended) BUT Ceril, Henryeta, the Butler, and Claus (the chef below the home) are all missing.

**Comment by Marwolf** [comment]
Unfortunately everything in the live v1 code is soon to be replaced and we aren't doing any more code changes to it as we are spending all of our time getting v2 ready. The server source is completely different and this should hopefully not be an issue on v2.
