### ISSUE TITLE
Dragon Slayer Quest - V2.0 BUG

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#655]
As you start the quest the Quest and talk to Oziach and try to click through all the available options, Oziach will pre-finish (end) the conversation. - Whenever you try to ask how to obtain all three pieces of the map.   -   bug probably not high priority.

I'll add more to this as I go & find more bugs.

**Comment by Bl0ds** [comment]
Did you first talk to guildmaster in varrock though?

**Comment by multi-talented** [comment]
"Did you first talk to guildmaster in varrock though?"
Yes. I also completed the quest.

**Comment by multi-talented** [comment]
Chris must of fixed the 1 hit bug already, it's just not pushed to the online dev (v2) server yet.

**Comment by Bl0ds** [comment]
Well I am using the same src and Oziach dialogue worked perfect. SO forgive me for guestioning you :D

**Comment by Christofosho** [comment]
So this is just a bug with "looping" the conversation? (ie: display the other options once one has finished running)

**Comment by multi-talented** [comment]
Quote: "So this is just a bug with "looping" the conversation? (ie: display the other options once one has finished running)"

Oziach will stop talking to you after you ask about the 2nd or 3rd map piece and u have to talk to Oziach again to continue. Not game breaking but inconvenience.

**Comment by multi-talented** [comment]
All options can be clicked, you just need to keep clicking "Talk to Oziach" to be able to.

**Comment by Christofosho** [comment]
This was fixed a long time ago, and found to be an issue with the timer on conversations being too short!
