### ISSUE TITLE
Bug boarding ship Brimhaven docks

### ISSUE THREAD

**Issue by lmsv-mx123** [Open-RSC/Game#656]
**Describe the bug**
Clicking on the boat on Brimhaven says "Nothing interesting happens" whilst it should trigger the dialogue of the customs officer in distance or should say "I need to speak with the customs officer ..."

**To Reproduce**
1. Click on the boat on Brimhaven
2. Server message of nothing interesting gets displayed

**Expected behavior**
The dialogue if the Customs official is near the player or the message informing the player to speak with them if they are far

**Screenshots**
![board_ship_brimhaven](https://user-images.githubusercontent.com/10690767/45589203-8568e380-b8e7-11e8-82e5-48652aa83e06.png)

**Additional context**
Need to verify that the customs officers at the karamja are correct

**Comment by lmsv-mx123** [comment]
On the same line after paying to board the ship on the other end the player should be placed outside the ship in Ardougne

![boarded_ardougne](https://user-images.githubusercontent.com/10690767/45589233-f14b4c00-b8e7-11e8-821e-77cb575bff80.png)

**Comment by multi-talented** [comment]
"Clicking on the boat on Brimhaven says "Nothing interesting happens" whilst it should trigger the dialogue of the customs officer in distance or should say "I need to speak with the customs officer ..."" - "Same problem persisted of "Nothing interesting happens" when clicking on the ship of Ardougne"

I Agree

**Comment by Bl0ds** [comment]
public class BoatFromBrimhaven implements TalkToNpcExecutiveListener,
		TalkToNpcListener, ObjectActionListener {
	
	public static final int SHIP = 736;
	public static final int OFFICER = 317;
	@Override
	public void onTalkToNpc(Player p, Npc n) {
		npcTalk(p, n, "You need to be searched before you can board");
		int menu = showMenu(p, n, "Why?", "Search away I have nothing to hide",
				"You're not putting your hands on my things");
		if (menu == 0) {
			npcTalk(p, n,
					"Because Kandarin has banned the import of intoxicating spirits");
			int menu2 = showMenu(p, n, "Search away I have nothing to hide",
					"You're not putting your hands on my things");
			if (menu2 == 0) {
				payDialogue(p, n);
			} else if (menu2 == 1) {
				npcTalk(p, n, "You're not getting on this ship then");
			}
		} else if (menu == 1) {
			payDialogue(p, n);
		} else if (menu == 2) {
			npcTalk(p, n, "You're not getting on this ship then");
		}
	}

	public void payDialogue(Player p, Npc n) {
		if (hasItem(p, 318)) {
			message(p, "The custom officer searches you...");
			npcTalk(p, n,
					"What is this we found here? I'm going to have to confiscate that");
			p.getInventory().remove(318, -1);
		} else {
			npcTalk(p, n, "Well you've got some odd stuff, but it's all legal");
			npcTalk(p, n, "Now you need to pay a boarding charge of 30 gold");
		}
		int pay = showMenu(p, n, "Ok", "Oh, I'll not bother then");
		if (pay == 0) {
			if (p.getInventory().remove(10, 30) > -1) { // enough money
				message(p, "You pay 30 gold", "You board the ship");
				p.teleport(538, 617, false);
				sleep(800);
				message(p, "The ship arrives at Ardougne");
			} else {
				playerTalk(p, n, "Oh dear I don't seem to have enough money");
			}
		} else if (pay == 1) {
			// NOTHING
		}
	}

	@Override
	public boolean blockTalkToNpc(Player p, Npc n) {
		return n.getID() == 317;
	}


	@Override
	public void onObjectAction(GameObject obj, String command, Player p) {
		if(obj.getID() == SHIP) {
			if(command.equals("board")) {
				if(p.getX() != 467 ) {
					return;
				}				
		Npc n = getNearestNpc(p, OFFICER, 5);
		npcTalk(p, n, "You need to be searched before you can board");
					
			}
		}		
	}
}

Quickly made. But something similar should work right? And we need the specific message!

**Comment by lmsv-mx123** [comment]
messages:
* I need to speak to the customs officer before boarding the ship
* I need to speak to the customs official before boarding the ship
(missing cases for captains)

**Comment by Bl0ds** [comment]
*Should have* Fixed the brimhaven dock. Was bit of journey learning how github works but Im gettin a hang of it...

Gonna look into ardougne now :)

**Comment by lmsv-mx123** [comment]
Yes ty also look around Karamja docks and Port Sarim that they get the condition there

**Comment by Christofosho** [comment]
#697
