### ISSUE TITLE
Cabbages "Item 228" [V2.0 NON-KOSHER]

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#665]
The cabbages inside the Draynor Manor's garden patch does not raise your defense by 1 like it does in kosher game.

Not to be confused with "item 18" cabbages.

**Comment by multi-talented** [comment]
Also the "item 228" cabbage in kosher RSC is not supposed to work for Black Knights Fortress quest, only "item 18" cabbage.

Unconfirmed if v2.0 OpenRSC followed this?

**Comment by Christofosho** [comment]
Black Knights Fortress cabbage selection is working as intended. Let me fix up the other issue. :)

**Comment by Christofosho** [comment]
#670
