### ISSUE TITLE
Gundai, Banker in mage bank. [V2.0 - NON-KOSHER]

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#666]
Banker (Gundai) in mage bank contain options for 'bank pins' and 'auctions'.

![banker](https://user-images.githubusercontent.com/43180426/45593100-386b2880-b94c-11e8-86df-da40312c54b5.PNG)

![banker2](https://user-images.githubusercontent.com/43180426/45593104-4456ea80-b94c-11e8-9420-b467ce9455dd.PNG)

**Comment by Christofosho** [comment]
Oops! Missed that one when I was adding the config!

**Comment by Christofosho** [comment]
#671
