### ISSUE TITLE
Immortal Vampire - [Vampire Slayer BUG] (V2.0) The stake doesn't work on the vampire in Vampire Slayer quest

### ISSUE THREAD

**Issue by Shin-Aska** [Open-RSC/Game#668]
**Describe the bug**
In Vampire Slayer quest, if you try to kill the vampire with the stake as the last hitting weapon, it wouldnt die. Also tried hitting the vampire with a stake first and swap to r2h then back to stake as the last hitting weapon and also tried killing with only stake as the weapon and the issue still persists.

**To Reproduce**
1. Do Vampire Slayer Quest
2. Get into the final phase after you obtain a garlic and a stake
3. Fight the vampire

**Expected behavior**
You should be able to kill the vampire with a main weapon first and stake as the last hitting weapon as seen on this video: https://plus.google.com/photos/photo/113301401337339325560/6533918151016819426

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Christofosho** [comment]
Looks like our code checks if you have the stake wielded with a hammer in your inventory.

**Comment by Shin-Aska** [comment]
oh, looks like i forgot a hammer, completely forgot to spawn that XD
