### ISSUE TITLE
Smuggling Karamja Rum using Teleport [V2.0]

### ISSUE THREAD

**Issue by Shin-Aska** [Open-RSC/Game#669]
**Describe the bug**
In Pirates Treasure, you shouldn't be able to smuggle the Karamja Rum using any form of teleportation

**To Reproduce**
1. Buy a karmja rum in karamja
2. Use any teleport spell

**Expected behavior**
The rum is removed from the inventory when the player teleports with the rum on their inventory

**Comment by Bl0ds** [comment]
Should there be a message to player when the rum is removed after teleporting?

**Comment by Shin-Aska** [comment]
@Bl0ds no, there is no message. It simply just disappears.

**Comment by Bl0ds** [comment]
Thanks. I'll add the update tonight :)

**Comment by Bl0ds** [comment]
Fixed. But would be good to test it when its compiled in the dev world
