### ISSUE TITLE
Add client setting to be able to display fatigue as real fatigue points and exp as real exp which is not divided by 4 and rounded

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#67]
See #53 and #66

**Comment by Marwolf** [comment]
This appears non-kosher. Is this still wanted to be done?

**Comment by Kenix3** [comment]
As a setting, yes I still want it. Will make development easier at worst.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
