### ISSUE TITLE
Fishing Trawler should have chance to award edible seaweed and oyster

### ISSUE THREAD

**Issue by lmsv-mx123** [Open-RSC/Game#674]
**Describe the bug**
Fishing Trawler does not have a chance to award edible seaweed and oyster

**To Reproduce**
1. Complete a game of fishing trawler
2. Inspect net and observe none of those two items are obtained

**Expected behavior**
A chance to obtain those items, should be less than the chance for junk

**Screenshots**
https://runescapeclassic.wikia.com/wiki/Fishing_Trawler

**Messages given when catching them**
 ..some seaweed
 ..an oyster!

**Comment by Christofosho** [comment]
#755
