### ISSUE TITLE
Merlin's Crystal quest - [v2.0.x - BUG]

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#688]
As a player starts the quest after talking to King Author and the knight's at the castle, Arhein (by the Catherby bank) has a missing chat option to talk about the deliveries - Resulting in a impossible completion of the quest!

I followed the guide from: http://runescapeclassic.wikia.com/wiki/Merlin%27s_Crystal
I also tried this with another player account.
Still no go.

**Comment by Bl0ds** [comment]
Quest can be completed but of course it is not the ideal way, you can just spam the ship and stow away.

To fix: What is the Dialogue for Arhein?

**Comment by Christofosho** [comment]
I've implemented the dialogue already, but via replays, it doesn't affect completing the quest. As long as another player is distracting Arhein, you should be able to board the ship.

**Comment by Christofosho** [comment]
Need clarification:
Can you distract Arhein and board the ship while he is distracted by another player?

**Comment by Bl0ds** [comment]
Is there a video about it? We could teleport the player inside a ship (or something that looks like a ship from inside) for couple seconds.

**Comment by multi-talented** [comment]
https://m.youtube.com/watch?v=EuSpZSd9x0Y
a good reference to the quest

**Comment by Christofosho** [comment]
How's this @multi-talented - I forget if it was completed?

**Comment by Christofosho** [comment]
@bl0ds?

**Comment by Bl0ds** [comment]
Yea should be good

**Comment by lmsv-mx123** [comment]
The teleport location should be 439, 504
And the player remains there for about 8 seconds
[19:27:10.065] (  NONE) You hide away in the ship
[19:27:11.305] (  NONE) The ship starts to move
[19:27:14.461] (  NONE) You are out at sea
[19:27:17.598] (  NONE) The ship comes to a stop
To arrive in the docks of the castle at 456, 520
