### ISSUE TITLE
Stats restoring [v2.0.1 - BUG/Non-Kosher]

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#696]
BUG:
As a player uses super set, sipping attack then strength and then defense; the player's stats will begin to restore in that same order. Stats will go from 118/99 to 117/99 one by one in same amount of time as sipping took.    *Although the messages you get when 99/99 is reached seems to be all at once at the same time.
|
KOSHER:
When the player sips the super sets, it will restore all at once at the same time. 

Also,
The stat restore relies on the game's internal clock rather than the amount of time from the initial sip. Sometimes in Kosher-RSC you can take a sip to 118/99 and it can immediately go to 117/99 because the internal clock was only a few seconds before changing.

**Comment by Christofosho** [comment]
#755
