### ISSUE TITLE
Firemaking Skill [v2.0.1 - BUG/NON-KOSHER]

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#715]
![fm fail](https://user-images.githubusercontent.com/43180426/45903723-a71b0c80-bdb8-11e8-8993-ff07dd875696.PNG)
^ Player has level 99 Firemaking and still fails to light the logs?!
My Kosher account used to have 74 Firemaking and never failed to light logs then.
Marwolf quoted:   "maybe the fail percentage isn't tied to level in the server".

Also, when you drop Oak+ logs** to ground and try to use a tinderbox on it, there is no message that appears. Nothing interesting happens

**Of course the game isn't supposed to use oak, maple, yew, magic logs as part of Firemaking skill. Only normal logs are used and EXP is increased per light based by the player's Firemaking level.

**Comment by Christofosho** [comment]
got u #716
