### ISSUE TITLE
Implement correct adding/removing friends behaviour

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#73]
There is currently no check on if the player you're attempting to add exists in the database.

- Do we have replays of messages when adding friends?
- Can't add friends when name is wrong?
- Can't add friends when you have too many?
- Can't remove friends because that user is not on your list?
- Can't add yourself as a friend?
- Can't remove yourself as a friend?
- Removing or adding a player with impossibly short name.
- Removing or adding a player with impossibly long name.
{Any other failure messages?}

**Comment by Kenix3** [comment]
Here is the message given when attempting to add a friend who doesn't exist
![image](https://user-images.githubusercontent.com/18299654/43659387-de3ae8a8-9729-11e8-8eba-766a0b875f1f.png)

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
