### ISSUE TITLE
Prayer is not draining

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#732]
<img width="378" alt="screen shot 2018-09-23 at 10 57 32" src="https://user-images.githubusercontent.com/16737510/45929458-20813f00-bf20-11e8-8e3a-9e0e06213859.png">
<img width="550" alt="screen shot 2018-09-23 at 11 00 03" src="https://user-images.githubusercontent.com/16737510/45929459-2119d580-bf20-11e8-80a7-7f58108d329e.png">

Killed KBD, prayer went from 99 to 1. (Likely a programmed effect of KBD)
Killed fire giant, prayer remained 99 despite multiple prayers running.

**Comment by Marwolf** [comment]
This was the result of changes in PR #719 for "Change event queues to LinkedHashMap to avoid many queued events, leading to abuse of packet spamming."

Assigning to @Christofosho

**Comment by Marwolf** [comment]
Verified fixed in PR #740

**Comment by multi-talented** [comment]
I noticed after using super attack and strength awhile and re-sipping, those stats stop draining as well.

**Comment by Marwolf** [comment]
After updating the dev test world with the current git repo code and testing, I was not able to replicate the problem. Drank multiple super str and super att potions and watched the temporary stats drop to normal over time.

<img width="484" alt="screen shot 2018-09-25 at 08 49 42" src="https://user-images.githubusercontent.com/16737510/46015315-fd7d9900-c09f-11e8-8844-429d0da8f90a.png">
