### ISSUE TITLE
Ranged is single-shot only

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#733]
Ranged 1v1 and ranging while another player attacks a NPC results in single shot only. No repeat firing until out of ammo.

**Comment by Marwolf** [comment]
This was the result of changes in PR #719 for "Change event queues to LinkedHashMap to avoid many queued events, leading to abuse of packet spamming."

Assigning to @Christofosho

**Comment by Christofosho** [comment]
#740
