### ISSUE TITLE
There is a lot of missing agility data

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#75]
http://runescapeclassic.wikia.com/wiki/Agility

- Ensure messages that each obstacle gives when you aren't high enough level is correct.
- Missing course-less obstacles / shortcuts.
- Missing quest obstacles.
- Once agility courses and obstacles are updated, they need to be tested to ensure behaviour matches official.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
