### ISSUE TITLE
Murder Mystery quest needs fixes

### ISSUE THREAD

**Issue by lmsv-mx123** [Open-RSC/Game#754]
**Describe the bug**
1 - When interrogating the family suspects, their dialogue option is not unlocked until:
 a) Player has retrieved for the first time the thread from the window -> unlocks the dialogue option of "Do you recognise this thread?" (This is not ok as option is available even before the player has retrieved the thread on the window. Note: if player destroys thread after searching, the option should still be present)
 b) Player has spoken to the Poison salesman on the option "Who did you sell Poison to at the house?" -> unlocks the dialogue option of "Why did you buy poison the other day?" (This one is ok as it does not appear until the player does the necessary step)

2 - Investigating scenery objects for poison might not be implemented:
After speaking with the culprit on why they had used poison and investigating the corresponding object no change is present. Example: consider David is the culprit. David says he used on the web found upstairs the mansion, the object investigate should change from "It looks like a Spiders Nest of some kind" to :
There is a spiders nest here
You estimate there must be at least a few hundred spiders ready to hatch
Its certainly clear nobodies used poison here.

Every other scenery object should change to the message of the family member having used poison (see wiki). (See on comments for more details).

3 - The family member's dialogue branch of "Do you recognise this thread?" does not check on the colour of the player's thread. Example if the player has green thread and they speak with David he replies: "No. Can I go yet? your face irritates me." when he should reply instead "Its some Green thread, like my trousers are made of.
Are you finished? I'm not sure which I dislike more
about you, your face or your general bad odour"

4 - Guard dialogue does not implement the case for poison on partial evidence. Player needs to find 3 pieces of evidence - the fingerprint, thread and poison investigation. Finding 1 or 2 pieces is partial evidence dialogue and is missing the poison dialogue branch ("I have proof one of the family lied about the poison"). The dialogue branch when player chooses "I have the fingerprints of the culprit" should start with the player saying "I have the fingerprints of the culprit".

5 - On quest finish on the paragraph where the guard says "We don't have many murders here in RuneScape [..]  We will hold him here under house arrest
Until such time as we can bring him to trial", needs to be checked for the culprit's gender and if its female changed to her

6 - The men around the area should have npc id 750 and are distinct from the regular man dialogue: https://runescapeclassic.wikia.com/wiki/Man_(Murder_Mystery)/Dialogue

**To Reproduce**
Described above, more info feel free to message on discord

**Expected behavior**
A close replica to the dialogue cases of
https://runescapeclassic.wikia.com/wiki/Guard_(Sinclair_Mansion)/Dialogue
https://runescapeclassic.wikia.com/wiki/Anna_Sinclair/Dialogue
https://runescapeclassic.wikia.com/wiki/Bob_Sinclair/Dialogue
https://runescapeclassic.wikia.com/wiki/Carol_Sinclair/Dialogue
https://runescapeclassic.wikia.com/wiki/David_Sinclair/Dialogue
https://runescapeclassic.wikia.com/wiki/Elizabeth_Sinclair/Dialogue
https://runescapeclassic.wikia.com/wiki/Frank_Sinclair/Dialogue

https://runescapeclassic.wikia.com/wiki/Beehive
https://runescapeclassic.wikia.com/wiki/Compost_Heap
https://runescapeclassic.wikia.com/wiki/Drain
https://runescapeclassic.wikia.com/wiki/Fountain_(Sinclair_Mansion)
https://runescapeclassic.wikia.com/wiki/Sinclair_Crest
https://runescapeclassic.wikia.com/wiki/Web_(Sinclair_Mansion)

**Additional context**

**Comment by lmsv-mx123** [comment]
Need to check quick on #2 if after speaking with any of the family members on the poison that all investigable scenery are changed to display the new message or not

**Comment by Bl0ds** [comment]
At which point did the 4th option unlock? 
![screenshot from 2018-09-25 20-29-47](https://user-images.githubusercontent.com/26518731/46031606-fedfad80-c101-11e8-97d0-f55cc714ea3a.png)

Started working on part 3, made the colors npc specific, it's not so bad as I thought at first

**Comment by lmsv-mx123** [comment]
For Donovan, his 4th option "Do you know why so much poison was bought recently?" i think that one appears after the player speaks with the poison salesman on "Who did you sell Poison to at the house?"

**Comment by lmsv-mx123** [comment]
I think on point 1 it has to do with a first time flag not being set or set to true for all players not sure which is the case. In any case the first time the player retrieves the thread it currently displays 
![regaining_thread](https://user-images.githubusercontent.com/10690767/46037014-96c2a480-c0cc-11e8-962f-e742758a66f0.png), and with the flag check the last line should not appear the first time the player gets the thread.

**Comment by Bl0ds** [comment]
Thanks. That cleared it up abit. Will continue to work on this tonight.

**Comment by Christofosho** [comment]
How'd this go @Bl0ds

**Comment by Bl0ds** [comment]
Guard dialogue needs some modifications. Quest is live on my test server. Should be finishable

**Comment by lmsv-mx123** [comment]
I think after the changes made and some corrections adapted, quest is close to replica
