### ISSUE TITLE
Implement correct item on death behaviour.

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#76]
On death, first thing that happens is _certain items_ are dropped. This can mean _certain items_ will be dropped if you have <= 3 items in inventory on death.

All (most?) stackable items are dropped on death even if you have <= 3 in the inventory.
Get with RSC Preservation folks for a list of known items that fit this criteria.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
