### ISSUE TITLE
Unable to log into dev world using same account as v1.

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#766]
When I try to log into Dev Test World, with the same account - It log in on the normal world.
I dropped a bread and tried switching world, turns out the bread was there after switching.

**Comment by LionRsc** [comment]
Turns out I might not be in the dev world even tho that's what I choose from the launcher.

**Comment by Christofosho** [comment]
This was established to be the wrong link? (Solved via Discord)
