### ISSUE TITLE
Inauthentic Feature List

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#778]
This ticket lists purposeful inauthentic features in the code. These features have been included or excluded due to the company's choice to leave them broken at the 2018 close date. At one time they were authentic in-game features and we have chosen to have them by default.

Changed Features
1) Kolodion spawns only once instead of 4 times
Original positions:
```
(712, 446, 441, 451, 3371, 3366, 3376, 4058),
(712, 448, 443, 453, 3368, 3363, 3373, 4060),
(712, 447, 442, 452, 3372, 3367, 3377, 4061),
(712, 444, 439, 449, 3370, 3365, 3375, 4062)
```
2) Gertrude spawns only once instead of 2 times
3) Desert heat will be added
4) Poison weapons able to poison other players will be added
5) Chat in RSC over a player's head would wrap, causing colours to revert to yellow on the second line of text. In our game we will allow the text to continue in the colour, based on the @ tags set.

**Comment by multi-talented** [comment]
Add the Fatigue Warnings to the list. Like when you mining and get close to 100%, get too tired to continue prior to 100%.
