### ISSUE TITLE
Multiple Colours Do Not Show Overhead

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#792]
**Describe the bug**
When typing a message, colours show in the typing box. More than one does not show over the character's head.

Players should be able to show more than one colour over their head at a time.

**Comment by Christofosho** [comment]
this magically worked for me today. huh.

**Comment by Kenix3** [comment]
![image](https://user-images.githubusercontent.com/18299654/48316626-3b813e80-e5b4-11e8-8213-16811748b5f2.png)
NOT working on v2
