### ISSUE TITLE
Pickpocketing aggression

### ISSUE THREAD

**Issue by Chanizu** [Open-RSC/Game#82]
You can reset the aggression by pickpocket targets resulting in you not getting attacked.

Pickpocket a target and as soon as your action fails/succeeds pickpocket again.
The target will say their text line then await the result of the next pickpocket if you started the action.

Upon failing a pickpocket the target engages you in combat.

Video
https://i.gyazo.com/1fa33f400787f037ef02974ac6f5c590.mp4

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
