### ISSUE TITLE
Launcher - Font Recourses Aren't Part of the Master

### ISSUE THREAD

**Issue by KeplerIO** [Open-RSC/Game#839]
**Describe the bug**
Code reference font resource directory which is not a part of the current master.

`Font font = Font.createFont(0, Utils.class.getResource("/data/fonts/" + fontName).openStream());`

**Screenshots**
![65c03a42460e109874b9a5070665069c](https://user-images.githubusercontent.com/26471970/46590184-44876900-ca66-11e8-82dd-248f27265606.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 64-bit

**Comment by Marwolf** [comment]
[fonts.zip](https://github.com/Open-RSC/Game/files/2454956/fonts.zip)
Should exist, not sure why it is not being picked up on GitHub. Will have to check this later.
