### ISSUE TITLE
Overhead Chat Text Should Keep Colour On Line 2

### ISSUE THREAD

**Issue by Christofosho** [Open-RSC/Game#851]
**Describe the bug**
When chatting, the colour in RSC did not persist if the chat wrapped to the second line over a player's head. 

We need the ability to toggle this on / off. Perhaps a config for configured chat, in general, would allow for this and other features to fall under the same umbrella?

**Comment by Kenix3** [comment]
v1 implemented this in commit e6fa4d30256bef5367d2d083d177b377d18ad922
Make sure this has a configuration value to be able to be turned on/off
