### ISSUE TITLE
banned players delete after 14 days of last login

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#86]
AccountManager.java - 

public void deleteBannedPlayers()

Looks to automatically delete after 14 days of being banned

String query = "SELECT rscd_players.user AS PlayerHash, rscd_players.username AS PlayerName, rscd_players.owner AS PlayerOwner, FROM_UNIXTIME( rscd_players.login_date ) AS PlayerLastLogin FROM rscd_players INNER JOIN users ON rscd_players.owner = users.id WHERE users.banned = '1' AND ( FROM_UNIXTIME( rscd_players.login_date ) <= ( NOW( ) - INTERVAL 14 DAY ))";

**Comment by Kenix3** [comment]
NOTE that AccountManager.java is not used in the normal server process. It is part of a separate compilation unit.

The intention is believed to be a cron that runs every so often that we do not currently have enabled.

**Comment by Marwolf** [comment]
"If it ain't broke.."
