### ISSUE TITLE
Convert bank note v1 invitems prior to transfer using SQL query

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#866]

**Comment by Marwolf** [comment]
<img width="387" alt="screen shot 2018-10-09 at 08 58 45" src="https://user-images.githubusercontent.com/16737510/46670966-8f59cb80-cba1-11e8-9fb9-9d5944494708.png">
These are the only inventory bank note items to have to deal with at the moment.

Subtracting 10000 from the item ID successfully de-bank notes it.

**Comment by KeplerIO** [comment]
Can this be merged with ticket #850 ? Also, I guess you're the only one with prod DB access, huh? Seems right up my alley.
