### ISSUE TITLE
Merge Android client and PC client code into the same folder or use imports

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#871]
Presently, we cannot keep the Android client code in sync with the PC client as they have separate folders with near-matching code (not counting the Android wrapper)

Either use an Android project to import the PC client's source when building OR merge the Android wrapper code into the PC client folder.

**Comment by KeplerIO** [comment]
I agree with the former. The android app should do nothing but execute the client proj.

**Comment by Marwolf** [comment]
After a large amount of work on this, the existing separate Android Studio project will remain as is for the time being due to time constraints and work required on other areas.
