### ISSUE TITLE
Chest's Changes (now and future)

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#88]
**Describe the bug**
the nature chest(335) is left out of open rsc, the hemenster(379) chest is not in open rsc, ardy chest ID is wrong(338 is right, 333 is wrong), and three additional chest ID's are in the chest def file(333, 337, 1197). Will leave them in game, confirm what they do, and add the original rsc id's and data in for later use, or cleaning up.

Added ID 335, 338, 379.
Left ID 333, 337, 1197.

Chest 337, and 1197 don't show up in Spawn Objects file, chest 333 shows up in black arm gang downstairs, and is 82(closed) and 81(open) in rsc.

**Comment by kInGkRiStOf** [comment]
chest 333 in open rsc, is chest 338 in rsc. Leaving 333 in, adding 338. Will work to see if 333 in open rsc is something special. Else, delete 333, and reassign as 338.

**Comment by kInGkRiStOf** [comment]
Don't have accurate teleport location for ardounge castle chest, can't attempt on current character.

**Comment by kInGkRiStOf** [comment]
chest 333 in open rsc is located in black arm gang down stairs, but is chest id 81 in rsc. fix in open rsc.

**Comment by kInGkRiStOf** [comment]
Last file change made, read original post for details^

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
