### ISSUE TITLE
bug tester in-game role

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#89]
Suggestion: create a bug tester role in-game that has teleport permissions but neuter the role so it can't interact with other players at all.

**Comment by Kenix3** [comment]
Set normal users to group = 10 and subscribers to group = 11
This should allow us more room for future staff roles.
Additionally, make sure client group numbers are the same as server group numbers.

**Comment by Marwolf** [comment]
Dev test server implemented instead.
