### ISSUE TITLE
Some actions not completing, being 'dropped' or exiting early.

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#893]
**Describe the bug**
Some actions are being dropped/exited prematurely. Woodcutting, dropping items, burying bones and maybe fletching/stringing bows.

**To Reproduce**
1. Start hacking away at a tree
2. Observe that sometimes the fail to cut the tree message will not appear. The action just ends without success or an official failure.

1. Start dropping items.
2. Eventually some of them will say they are being dropped and never leave the inventory.

**Expected behavior**
Either a success or failure of said steps. Instead the action just stops.

**Screenshots**

https://youtu.be/MRHe2F_jxoU
https://youtu.be/2BM93p-yexM

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by Christofosho** [comment]
Events must not be getting properly removed from the event queue. Whoever works on this needs to check and see if the event remains in the queue unintentionally.

**Comment by Zephedge** [comment]
My first hunch was that this was only related to items entering and exiting the inventory, such as a **successful** mining or woodcutting even. However, even when trying to mine an ore that I have no chance of getting, the automatic pickaxing stops prematurely, so it is not just on a successful inventory change event. 

I have not noticed and dropped actions for walking, attacking, or using the interface.

**Comment by Christofosho** [comment]
I'm hoping my fix is decent enough. We will see, when this hits prod.
