### ISSUE TITLE
Extra right click option Al Kharid Banker

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#894]
**Describe the bug**
Bankers in Al Kharid have an extra context menu that just says "Banker"

**To Reproduce**
1. Right click on Al Kharid Banker

**Expected behavior**
Should not be a thing.

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/46992544-8c4a6800-d0d8-11e8-8284-9e648e47ddfb.png)

**Comment by Christofosho** [comment]
Interesting. It shouldn't even have a bank option. Let me check tonight.

**Comment by Christofosho** [comment]
#892
