### ISSUE TITLE
Typo - Extra character when cooking Bread Dough on range or fire

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#896]
**Describe the bug**
Cooking bread dough on a range or fire produces an extra character in the word dough, typod as 'd dough'

**To Reproduce**
1. Cook bread on fire or range

**Expected behavior**
the word 'dough'

**Screenshots**
![image](https://user-images.githubusercontent.com/995993/46994122-f7983800-d0e0-11e8-9373-1f930cbcbdb6.png)

![image](https://user-images.githubusercontent.com/995993/46994128-fd8e1900-d0e0-11e8-9942-783c73228732.png)

**Comment by Christofosho** [comment]
#892

**Comment by lmsv-mx123** [comment]
Should only be able to cook dough on range
