### ISSUE TITLE
Gold coin drops are often or always 1gp

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#897]
**Describe the bug**
Some or all gold coins dropped is only in denominations of 1

**To Reproduce**
1. Get a gold coin drop

**Expected behavior**
More variety of gold in a pile

**Additional context**
Unsure if all gold is affected by this, but at least Guards and bandits drop only 1 gp

**Comment by Christofosho** [comment]
Did you see any NPCs that drop more than just 1gp?

**Comment by Zephedge** [comment]
So far I have not found any drops more than one, I have only added Giants to me sample size though.

**Comment by Christofosho** [comment]
27% 1 gp for that guard in question. I guess my rates need work. It was quite difficult to discern the weights of gold, to be fair. :P
