### ISSUE TITLE
Bandit Camp

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#898]
Submitted by Discord user: kruc1al

Fat Tony npc is aggressive - hes supposed to sell doughs and he attacks with no combat level, same with noterazzo the general shop npc. In the original RSC the higher bandits- eg. black heather had a chance to drop silver and swordie certs- 1 at a time and havent seen anything yet. Also theyre only dropping 1gp at a time.

**Comment by Christofosho** [comment]
lol this is hilarious. looking now

**Comment by Christofosho** [comment]
#892
