### ISSUE TITLE
Merlin's Crystal Quest - Candlemaker and wax bucket for black candle

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#899]
**Describe the bug**
During the Merlin's Crystal quest, when you talk to the candlemaker he is supposed to tax your bucket of wax and give you the black candle. He does not take the bucket of wax and does give you the candle.

**To Reproduce**
1. Get wax bucket from beehive in Seers
2. Talk to Candlemaker in Catherby
3. Finish two dialogs with him about the black candle
4. Receive candle without having wax bucket taken from you

**Expected behavior**
Candlemaker should either cake the whole bucket or take wax bucket and give back empty bucket. Unsure which is kosher.

**Screenshots**
![image](https://user-images.githubusercontent.com/995993/46994499-b3a63280-d0e2-11e8-983a-047356045012.png)

**Comment by Christofosho** [comment]
#908
