### ISSUE TITLE
Guard Level 28 Wrong Drop (Silverlight Key 2)

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#900]
**Describe the bug**
Killed a Guard by the silk stall in Ardy and received Silverlight Key 2.

**To Reproduce**
1. Go to Ardy
2. Kill Guards. Not a guaranteed drop.

**Expected behavior**
This is not a valid drop.

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/46995860-8bb9cd80-d0e8-11e8-94e9-d624c5a0f039.png)

**Additional context**
I had fully completed Demon Slayer long before this.

**Comment by Christofosho** [comment]
For any developer working on this: there are many guard IDs in the database. They all have different drops from one another. It is painful, because we don't have the data to support the drop table. In this case, it might be either a misnumbered  item id, or I may have missed this NPC completely.

**Comment by Bl0ds** [comment]
I believe the Guard ID in that case is 321

**Comment by Christofosho** [comment]
#892
