### ISSUE TITLE
Mining seems bugged in v2

### ISSUE THREAD

**Issue by CamelPooBoy** [Open-RSC/Game#901]
I am not sure which is kosher behavior, but in my opinion it should not behave this way.

The first bug I describe: when using Rune pickaxe to mine rocks, it displays animation of "Steel or Iron Pickaxe" above the player´s head as seen in this picture.

![camelpoomine](https://user-images.githubusercontent.com/43058162/46996347-04d71600-d125-11e8-9987-a09b8154b264.jpg)

When clicking a rock, either coal or mithril rock, especially with mining level of 69, it should automately display "You swing your pick at the rock" "You succeed only scratching it" or "You manage to obtain some Ore X"

It does work at times, but sometimes I have to click the rocks up to 30 times and it only says "You swing your pick at the rock" and it does not give any info either you succeed on obtaining ore or not.

It does work normally at times, but it seems bugged from time to time after I tried to mine some 5 minutes.

**Comment by Christofosho** [comment]
#893

**Comment by Christofosho** [comment]
#892 potential fix, will track in the related ticket.
