### ISSUE TITLE
Friends list issue - Unreliable fetching of friends

### ISSUE THREAD

**Issue by ZephORSC** [Open-RSC/Game#904]
**Describe the bug**
Logging in results in unreliable behavior concerning the friends list. So far three different results have occurred:
1. Fetches zero of my friends from the list
2. Fetches only one player from my friends list (Player named Red)
3. Fetches what I assume is my entire friends list.

**To Reproduce**
1. Log in
2. Repeat until different friends list

**Expected behavior**
Full friends list should be fetched from database

**Additional context**
I believe player Red might be the first person I added to my friends list?
Additionally, I have not been able to reproduce this bug 5 minutes after experiencing it the first time.

**Comment by Marwolf** [comment]
I noticed only seeing a single friend when I logged in as well this morning.
