### ISSUE TITLE
Bank window stutter on exit

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#906]
**Describe the bug**
Upon exit the bank window, either by the close window button or by clicking outside of the window, the window appears to close, open again and then close again. Functionality appears unaffected. 

**To Reproduce**
1. Go to bank
2. Open bank window
3. Close bank window

**Expected behavior**
A single window close

**Desktop (please complete the following information):**
 - OS: Windows 10

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by Christofosho** [comment]
confirmed. assigning to me

**Comment by Christofosho** [comment]
#892
