### ISSUE TITLE
Quest points set to zero; need recalculated due to V1 -> V2 migration

### ISSUE THREAD

**Issue by ZephORSC** [Open-RSC/Game#907]
**Describe the bug**
Some players quest points were reset to zero during the migration. Need to completely recalculate quest points based in completed quests. 

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/47030663-1c6dc900-d13c-11e8-9ec5-568ec96c6110.png)

![image](https://user-images.githubusercontent.com/995993/47030451-c00aa980-d13b-11e8-9d80-e8439066b889.png)

**Additional context**
Completing new quests going forward adds to the total starting from zero. Finished Merlin's crystal and now I have 6 quest points and a bunch of quests done.

**Comment by Christofosho** [comment]
We should create a map which houses all of the quest information. Right now each quest has its reward in a different place. Difficult to follow.

**Comment by KeplerIO** [comment]
This requires checking each player with a quest of stage = -1 in DB and adding appropriate amount of QP per finished quest... nightmare..

**Comment by multi-talented** [comment]
Earlier today on single player mode, I made another player, and ::questcom 0-49 for all quests completions. I resulted in a different number of qps of 104. Was resulting in 107 before.

**Comment by lmsv-mx123** [comment]
For all quest completion should be 112 not 107; 107 is completing almost all quests except legends and a 1 QP quest

**Comment by multi-talented** [comment]
So basically it's been wrong all along lol (and getting worse). I never done all quests in the real game, so idk myself for sure. Tried to have someone verify max points one time but no one responded to me.

**Comment by Marwolf** [comment]
I'll check into this tonight. Shouldn't be too hard to write a SQL query to do the heavy lifting.
