### ISSUE TITLE
Captain Tobias, Seaman Lorris and Seaman Thresnor should sail you to the Eastern Karamja

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#909]
**Describe the bug**
In Port Sarim, Captain Tobias, Seaman Lorris and Seaman Thresnor currently sail you to the dock in Brimhaven, however they are supposed to sail you to the dock on Eastern Karamja

**To Reproduce**
1. Go to Port Sarim
2. Speak to Captain Tobais, Seaman Lorris or Seaman Thresnor
3. Ask them to sail you to Karamja

**Expected behavior**
Player character should be placed on the Eastern Karamja dock.

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/47055069-98d7ca80-d183-11e8-8df9-653bf7dddf0d.png)

**Comment by KeplerIO** [comment]
Please verify the exact coordinates of the player teleport to Karamja upon talking to the sailors. This can be easily fixed in the menu selection for the chat options.

**Comment by Bl0ds** [comment]
This is weird.

**Comment by Zephedge** [comment]
@Christofosho Told me on Discord that this should be fixed in the next version, a proper acknowledgement from him in here is probably best though

**Comment by Christofosho** [comment]
Yep, it'll come out #892
