### ISSUE TITLE
Withdrawl All stops at 1

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#91]
I assume drag and drop for items in the bank isn't going to happen, so can we add an if statement into the "withdraw all" function in that it will stop at 1? so:

if (bank has > 1 of item && withdraw all is selected) {
withdraw all but 1;
}
else if(bank has == 1 of item && withdraw all is selected) {
withdraw all;
}

basically trying to withdraw all will result in needing to click it twice to actually withdraw everything, but clicking it once will keep the item in its original bank space. Quality of life update, and would make people save hours on sorting their banks just right.

**Comment by Kenix3** [comment]
I don't have a problem with this enhancement, but it should probably be an addition to withdraw all.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
