### ISSUE TITLE
Starting Scorpion Catcher quest automatically sets quest text color to green

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#911]
**Describe the bug**
Initial start of the Scorpion Catcher quest turns the text color green in the quest list instead of yellow. 

**To Reproduce**
1. Go to Sorcerer's Tower
2. Click on Thormac the sorceror
3. Start the quest

**Expected behavior**
Quest text should be yellow until completion of quest

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/47056620-3f739980-d18b-11e8-96a0-e4293d9702c6.png)

**Additional context**
So far progress can still be made in the quest even though the green text would indicate complete of said quest.

**Comment by KeplerIO** [comment]
This is an issue with every quest. I've been working through them myself and noticed this.

**Comment by Christofosho** [comment]
#973
