### ISSUE TITLE
Highscores list isn't synced with highscores (tabs?)

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#915]
**Describe the bug**
Website highscores long list(all players for a certain skill) isn't syncing with the skills for individual players, so if i go to my player scores, strength can be 90, but in the long list of strength with all players, it'll show 54, or whatever it was at original update.

**To Reproduce**
Check individual player scores, then go to long list of highscores and see the difference.

**Expected behavior**

**Additional context**
Miss you Marman.

**Comment by KeplerIO** [comment]
This should be using the openrsc_curstats table?

**Comment by Marwolf** [comment]
Use a super pot and suddenly...

**Comment by KeplerIO** [comment]
😂 okay good point
