### ISSUE TITLE
Bug Report From Main Website

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#916]
**Is your feature request related to a problem? Please describe.**
Yeah, put a bug report page on the updated site

**Describe the solution you'd like**
www.openrsc.com/elite/bugreport

**Describe alternatives you've considered**
Pesticides.

**Additional context**
Sometimes, the difference in temperature between the sunny area's and the shady area's can range as much as 40 degrees Fahrenheit(not game related).

**Comment by Marwolf** [comment]
Added
