### ISSUE TITLE
Ranged gives incorrect exp (wrong by a few exp)

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#917]
Only tested two monsters(Dungeon Rats(16), and Goblins(13)). Both gives wrong exp, I assume this is wrong for many more.

Dungeon rats(16) give 48 instead of 52 ranged exp
Note normal melee combat gives correct exp of 39 in style and 13 in hits.

Ranged combat gives no hit point experience but instead gives it as range experience.
> You get no Hits experience when ranging so the total ranged experience per kill comes from the monsters base experience plus the experience you would normally get in Hits.

Problem is that when ranging you do not get the correct exp, maybe there is a small exp flaw in the formula when calculating range exp, have not tested other critters.

http://runescapeclassic.wikia.com/wiki/Dungeon_rat
http://runescapeclassic.wikia.com/wiki/Ranged_training
http://runescapeclassic.wikia.com/wiki/Ranged

Goblin(13) gives 48 exp instead of 46 exp.
http://runescapeclassic.wikia.com/wiki/Goblin

**Comment by Christofosho** [comment]
#892
