### ISSUE TITLE
Holy Grain Quest - Black Knight Titan's Health bar is too long

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#918]
**Describe the bug**
Boss NPC Black Knight Titan has a very long health bar. Only has around 144 actual health though.

**To Reproduce**
1. Attack Black Knight Titan

**Expected behavior**
Health bar should be scaled to normal length

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/47125599-647f0f80-d252-11e8-86e4-0a0a17c4287f.png)

**Comment by multi-talented** [comment]
Most high level npc's are effected by this glitch, sometimes the initial life of the npc will appear normal but after respawn it'll be glitched and sometimes have a 1hp (1 hit) bug as well.
