### ISSUE TITLE
Holy Grail Quest - magic golden feather always points north

### ISSUE THREAD

**Issue by Zephedge** [Open-RSC/Game#920]
**Describe the bug**
Magic golden feather item always says "the feather points north"

**To Reproduce**
1. Proceed through Holy Grail quest until receiving magic golden feather
2. Choose blow option on magic golden feather

**Expected behavior**
Clicking the blow option on the feather should give the player the cardinal direction they need to travel to get to Sir Percival's sack in the goblin village.

**Screenshots**

![image](https://user-images.githubusercontent.com/995993/47126239-95ad0f00-d255-11e8-9621-d42ba51d4fe0.png)

![image](https://user-images.githubusercontent.com/995993/47126634-74e5b900-d257-11e8-840d-ec7f39d1385c.png)

**Comment by Bl0ds** [comment]
Should be fixed when the latest code is put live
