### ISSUE TITLE
Unable to complete digsite quest (missing workmen)

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#924]
Submitted by Discord user: Troll

I completed the 3rd exam for the digsite quest and when I go down the winch shaft there is supposed to be a workman that will give me a key but he isn't there. I am unable to progress any further in this quest

**Comment by Zephedge** [comment]
Can confirm this is an issue making the quest unable to be completed.

**Comment by LionRsc** [comment]
Adding to this, Arcenia root should be in the ground within the main dungeon. Those are no where to be seen.
Using Ropes on shaft does not take/use the robe as intended.

Quest looks partial done, and seems not to be completely implanted.

**Comment by KeplerIO** [comment]
Claiming ticket.
