### ISSUE TITLE
Observatory Quest - Missing Quest Reward

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#933]
After seeing the Taurus sign in completing the quest I was not rewarded with a Super Strength potion.
Also the professor forgets to take his items as you complete the quest. (Planks and lens)

**Comment by Bl0ds** [comment]
but but the reward is random :D

**Comment by lmsv-mx123** [comment]
The reward should be according to the constellation

**Comment by LionRsc** [comment]
I appreciate you taking the time to look into the code, consider it a future project to look into - when more information is present.

I'm sure it was Taurus, and sure I did not get super strength potion. (I might have gotten experience - did't look as I was expecting Taurus to give item).

My guess would be pictures shown in game to the player ain't linked to the right rewards.
- This quest is bit dangerous for certain account types. (that do not want certain experience) and have no way to check ahead.

Additional information:
I have some notes trying to figure out what in game picture gave what reward before the solution was added to wiki. (from 2017:)
http://prntscr.com/l93v55

**Comment by lmsv-mx123** [comment]
> My guess would be pictures shown in game to the player ain't linked to the right rewards.

Yea by the looks of what you comment that would be the case, the wiki pictures are of what the constellations should be, as I along with another preservation folk rerolled to make sure and get the dialogue.

> This quest is bit dangerous for certain account types. (that do not want certain experience) and have no way to check ahead.

I do not get what you mean, you can reroll on the telescope if you want to try for another reward. When you continue the dialogue with the professor that is when you are given the reward for the last constellation.

**Comment by lmsv-mx123** [comment]
Tested locally and didn't give me trouble, fixed for the moment dialogue on reward #972 as well a bit of behaviour that was missing. Make sure to test again, if the problem is presented again it could be due to server lag (all images verified to match their corresponding reward).

**Comment by LionRsc** [comment]
Quest would be dangerous if pictures did not match in game reward. After your testing we know they do match, so thanks a lot.

I did re-roll in order to get Taurus :)

I really appreciate you taking your time to double check, I'm sorry  the result was unable to being reproduced. Keep up the good work - stay awesome.
