### ISSUE TITLE
Verify Pickaxe swings

### ISSUE THREAD

**Issue by lmsv-mx123** [Open-RSC/Game#938]
**Describe the bug**
Verify number of swings for pickaxes

**To Reproduce**
Observe number of swings on runite rocks since these have the highest fail rate

**Expected behavior**
Bronze pickaxe - 1 swing
Iron pickaxe - 2 swings
Steel pickaxe - 4 swings
Mithril pickaxe - 6 swings
Adamant pickaxe - 9 swings (discussion on discord)
Rune pickaxe - 12 swings

**Additional context**
https://github.com/Open-RSC/Game/blob/2.0.0/server/plugins/com/openrsc/server/plugins/skills/Mining.java#L124

**Comment by Christofosho** [comment]
#944
