### ISSUE TITLE
Unable to steal from Tea Stall varrock east

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#939]
I'm unable to steal from thetea stall, I have passed the req. of 5 thieving.
http://runescapeclassic.wikia.com/wiki/Tea_stall

**Comment by KeplerIO** [comment]
Hello Lion, does anything at all happen when you do this? Message, weird movement?

**Comment by LionRsc** [comment]
Dosen't matter from what side you try, went the hole way around trying.

You get following message: "Nothing interesting happens"
You are able to walk away right as you click to steal - implying there is no action going on(or it's an instant action).
No icon above head.
No exp gained.
No message above any guard or seller around the stall.

**Comment by lmsv-mx123** [comment]
there should not be bubble icon, but there should be exp/fatigue and cup received upon steal, also like a 5 sec respawn time

**Comment by LionRsc** [comment]
Ahh, guess that was a v1 non-kosher thing.
No exp gain, no cup gained, I assume no fatigue.

**Comment by lmsv-mx123** [comment]
Watching from Shauns vid I think it should be harder to thieve from that stall in comparison with the Ardougne Stalls (e.g. cannot thieve if Tea seller is not busy or something like that)

**Comment by LionRsc** [comment]
Did not know that, imo that sounds like bad design. Not being able to thieve a low level stall alone, without anything hinting that you need a second player to help you.

**Comment by LionRsc** [comment]
Did not work having a second player talking to the merchant.

**Comment by Marwolf** [comment]
Other than the bubble, did this work in v1?

**Comment by lmsv-mx123** [comment]
> Not being able to thieve a low level stall alone, without anything hinting that you need a second player to help you.
Well the seller did give a dialogue to the player but yea it is a bad design giving them difficulties to thiev from, probably the catch rate could be loosened up like the Ardougne Stalls

**Comment by multi-talented** [comment]
Is there rsc+ recording evidence of a player being able to steal tea from tea stall? If i recall right in rsc, you wasn't able to steal from stalls in f2p areas. (In rs2+ you can)

**Comment by KeplerIO** [comment]
The wiki says this specific stall should be "thievable" (assuming the player was a member). Successful steal should grant 16xp and a tea.

**Comment by lmsv-mx123** [comment]
I don't think you could not steal from if the player was in p2p world. The thing is the tea seller seems like he gave people hard time stealing tea from and few attempted to steal while he was busy to be able to thief.

**Comment by lmsv-mx123** [comment]
Fixed #962
