### ISSUE TITLE
Official RSC Launcher Behaviour

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#94]
Thanks to Ornox for the write up
--------------------------------------
@subjectivelyobjective the ending on the cache files is a checksum of the cache file
its probably to prevent browsers from caching the file locally
if you want another fun fact
their http server will accept /content0_, /content0_asdafaf, /content0_14524532 as all the same file
same with rsclassic.jar
the web server looks at the request as starting with /rsclassic and containing .jar
so
http://classic1.runescape.com/rsclassic.jar
http://classic1.runescape.com/rsclassic.jarlolnoob
http://classic1.runescape.com/rsclassicFuckinGGNerd.jar
http://classic1.runescape.com/rsclassic_imTotallyLegitHash.jar
are all valid :smiley:
https://hastebin.com/exajekoboy.java
a very rough snippet of code i wrote that mimics the behavior of their server
and yes, /index.html isnt the same as /
their server literally expects / to return the page seen at http://classic1.runescape.com/
also
the hashes you see at the end of content0_
is from /contentcrcs
https://hastebin.com/oyemozuxok.java
:wink:
idk if anybody else bothered writing an http server based on how it actually operates
https://hastebin.com/vocequkeyu.java
here is what i ended up with for jav_config.ws, and plugin.js
its not complete
but its enough to run a client in a valid configuration
via methods rsc+ uses to launch rsc, and the official legacy client launcher
which it actually tricks into running, except if you modify the jar and destroy the signature
which the signature has to be removed because you have to patch out the codebase check for if its running on runescape.com in the client(edited)
https://hastebin.com/xahibigamu.java
this is also how they reply to requests roughly (?) via http
its accurate to what i was testing
they also throttle downloads to roughly 42KB/s, and its why the vanilla client takes so long to load as they dont seem to cache the content files (but the applet does!)(edited)
@subjectivelyobjective hopefully that answers your question + more
it all comes down to how accurate you want to mimic their servers in the end, i chose to replicate many behaviors (even ones invisible to the user) to try to get a closer to "pure" server(edited)
and because... its just nice to understand how things work, why theyre the way they are, and maintain their uses in the process... if you're just guessing with every decision you make, youre not replicating RSC. you're making your own game

**Comment by Marwolf** [comment]
The one thing that may make this not usable is that it replies on an applet.

Modern browsers do not allow java applet execution, hence use of downloaded executable jar.

**Comment by Kenix3** [comment]
Agreed. Intent was documentation.
