### ISSUE TITLE
Panning - Mistakenly gets duplicated trays when finding golden nuggets

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#940]
After panning, when searching your tray.
There is a random chance you'll end up with a tray with golden nuggets and an empty tray. (I assume when-ever you roll the golden nugget chance)

**Comment by KeplerIO** [comment]
Note to self: If player rolls golden nuggets, server delete empty pan from inventory, spawn pan containing nuggets.

**Comment by Christofosho** [comment]
#944
