### ISSUE TITLE
Dwarf Cannon Quest - Question Regarding fence dmg & dwarf remains not being removed

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#942]
Question regarding the correctness of the following two:
1. Got hit for 10 trying to repair it fence. (Wiki says you should always be hit a 2)
2. Dwarf remains are not removed from inventory doing the quest.

**Comment by lmsv-mx123** [comment]
Not always, in my replay sometimes I got hit for 3, not higher though and most of the times was 2.

**Comment by lmsv-mx123** [comment]
Should be fixed in #1089
