### ISSUE TITLE
Man NPC has conversation

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#96]
Talking to the man NPC in Lumbridge causes him to return conversation. They did not talk in the original game.

Player: Hello
Player: How's it going?
Man: Do i know you?
Player: No, i was wondering if you had anything interesting to say

Player: Hello
Player: How's it going?
Man: I think we need a new king
Man: The one we've got isn't very good

**Comment by SideW1nder** [comment]
They do have conversations in real rsc, each and every one of them with the npc id 11.

They also have several random dialogues. Matter of fact 14 different dialogues.

**Comment by Marwolf** [comment]
Verified. Okay, closing.

https://runescapeclassic.wikia.com/wiki/Man/Dialogue
