### ISSUE TITLE
Quest List Color Issue

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#960]
Submitted by Discord user: Grimboe

Just started the Romeo & Juliet Quest, in my quest log the quest is showing up green in color rather then yellow. I'm not sure if this is a problem with every quest

**Comment by LionRsc** [comment]
It is that for every quest.

**Comment by KeplerIO** [comment]
Yes this is reoccurring issue. It is for every quest.

**Comment by Christofosho** [comment]
There is no yellow.

Also, this will need a new issue with the affected quests if it's got a problem (ie: you didn't complete it but it is showing complete).
