### ISSUE TITLE
Fire giants drop

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#963]
Had a 1 coin drop.
Wiki states he drops 15, 50, or 60 coins at a time.

Not dropping anything from the rare drop table. (gems, half keys, half shields).
http://runescapeclassic.wikia.com/wiki/Fire_Giant

**Comment by Christofosho** [comment]
Weird! I have him set as:
put(344, new int[] {15, 60});

... Let me see if this is weird or I missed something!

**Comment by Christofosho** [comment]
#966
