### ISSUE TITLE
Expand highscores

### ISSUE THREAD

**Issue by LionRsc** [Open-RSC/Game#964]
**Is your feature request related to a problem? Please describe.**
Want to check how well you fare on the highscore but not quite in the top 30 of a skill, we need to be able to dig deeper into the high scores. 

**Describe the solution you'd like**
I suggest at least being able to see top 200 in a current skill/skill total. If having 30 per page I suggest 300. 

**Additional context**
http://prntscr.com/l8l2nz

**Comment by Marwolf** [comment]
Highscores now display all players with a javascript quick search
