### ISSUE TITLE
Server configuration variables should be read from the database rather than a file

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#97]
This would simplify setup for those who aren't as technically inclined or who don't have strong opinions on configuration. Less noise for people to decide values.
We would leave the database configuration in the file.

We also would want to modify the client configuration file. Likely we would want the client to send a packet to the server to request config state.

**Comment by Marwolf** [comment]
Client packet feature for reading config already implemented by Kenix.

Reading config from database would be good for showing on a website what features are enabled automatically.

**Comment by Marwolf** [comment]
Will re-evaluate in v2.
