### ISSUE TITLE
Identify Herbs While In Combat

### ISSUE THREAD

**Issue by kInGkRiStOf** [Open-RSC/Game#978]
**Describe the bug**
Spam clicking herbs while in combat allows you to identify them. The first click shows the message " you can't do that whilst you are fighting" and the second click identifies the herb. Does not work with bones. 

**To Reproduce**
Do that^

**Expected behavior**
can't do shit while in a fight!

**Additional context**
I enjoy pranking my friends. Try this: take their hat, jacket, gloves, etc, and wrap them up in tape, like A LOT of tape, but leave a portion visable, so they know it is theirs. Then leave it back int the place it was found.

**Comment by Christofosho** [comment]
I can't replicate this. Is there some trick to it? Can you record a video of it?
