### ISSUE TITLE
Bandit Camp

### ISSUE THREAD

**Issue by openrsc** [Open-RSC/Game#996]
Submitted by Discord user: kruc1al

Noterazzo takes 1-2 tries before shop opens up, bandits only drop 1 gp/runes at a time, still missing a net respawn. Also as a side note cooking is a bit slower/needs to be sped up slightly.

**Comment by Christofosho** [comment]
This needs more information.

**Comment by Marwolf** [comment]
Shop opening should be fixed now. 

https://runescapeclassic.wikia.com/wiki/Bandit_Camp
Only says there is a "Net / bait fishing spot"

Need a replay to show there was a net respawn.

Closing for now.
